### ISSUE TITLE
Office.js excel web app issue - Uncaught Sys.ArgumentNullException: Sys.ArgumentNullException: Value cannot be null. Parameter name: conversationId

### ISSUE THREAD

**Issue by nasatechie** [OfficeDev/office-js#1084]
Hi There, we are developing few web applications rendered in task pane (in angular, react etc) using  on Office.js API, the issue we are facing is - we are trying to navigate from one application to another inside task pane for which we are using iframes. In our case our both apps (say app1, app2) run on the same port but as two different child applications, because of the same origin policy, office.js is throwing the below issue to render 2nd app inside first app if we try using iframe inside task pane.

below is the error trace, any help is much appreciated:

Uncaught Sys.ArgumentNullException: Sys.ArgumentNullException: Value cannot be null.
Parameter name: conversationId
    at Function.a.create (https://appsforoffice.microsoft.com/lib/1/hosted/excel-web-16.00.js:24:86879)
    at Function.a.argumentNull (https://appsforoffice.microsoft.com/lib/1/hosted/excel-web-16.00.js:24:87540)
    at Function._validateParameterType (https://appsforoffice.microsoft.com/lib/1/hosted/excel-web-16.00.js:24:92187)
    at Function._validateParameter (https://appsforoffice.microsoft.com/lib/1/hosted/excel-web-16.00.js:24:91571)
    at Function._validateParams (https://appsforoffice.microsoft.com/lib/1/hosted/excel-web-16.00.js:24:90987)
    at new Microsoft.Office.Common.ClientEndPoint (https://appsforoffice.microsoft.com/lib/1/hosted/excel-web-16.00.js:24:98742)
    at Object.connect (https://appsforoffice.microsoft.com/lib/1/hosted/excel-web-16.00.js:24:108381)
    at OSF.InitializationHelper.setAgaveHostCommunication (https://appsforoffice.microsoft.com/lib/1/hosted/excel-web-16.00.js:24:127880)
    at o (https://appsforoffice.microsoft.com/lib/1/hosted/office.js:41:26228)
    at d (https://appsforoffice.microsoft.com/lib/1/hosted/office.js:41:3609)

**Comment by Rick-Kirkham** [comment]
@keyur32 Can you answer or reassign to someone who can?

**Comment by nasatechie** [comment]
Team, is there any fix available for this scenario? Happy to provide more info :)

**Comment by keyur32** [comment]
HI @nasatechie , is this affecting you in a way?  I think the exception that is being thrown is an internal one seperate from your add-in.. 

Also does the exception always appear while debugging or only after certain operations?

**Comment by keyur32** [comment]
assigning to @lumine2008 from our APIs team to also help

**Comment by keyur32** [comment]
Actually, ignore previous comment..

This appears to be a runtime question.  @smaremanda can confirm but I believe, your taskpane can't navigate to a different domain. The page it is going to needs to be in the same sub domain or in the allowed domains list in the manifest.

**Comment by nasatechie** [comment]
Hi @keyur32  & @smaremanda , the issue is consistent as we reproduced this multiple times and it even occurred with sample applications deployed without any business logic. what I mean by this is, our app1 and app2 both are in same domain and we want to render app2 inside app1 (which uses an iframe), to make things simple app1 button click should render app2 inside app1 iframe.

**Comment by nasatechie** [comment]
Hi @keyur32 and @smaremanda , any update on the above issue?

**Comment by smaremanda** [comment]
hi @nasatechie - for security reasons we dont allow nested iframes to execute Office.js APIs. My question back to you: why do you need your app2 to be inside of an iframe [esp if it shares the same domain as app1]. why couldnt they simply be inline [using divs for example]?

**Comment by keyur32** [comment]
hi @nasatechie, we didn't hear back from you. Closing this for now, but feel free to re-open later.
