### ISSUE TITLE
[Word Online] Error on document body search with matchWildCards:true

### ISSUE THREAD

**Issue by mmoore-3lc** [OfficeDev/office-js#1141]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

## Expected Behavior
Executing the below code returns a RangeCollection object as it does on Word Desktop and Word for Mac:

```
searchResults = context.document.body.search("([{])@*([}])@", {
        matchWildCards: true,
        ignorePunct: true,
        ignoreSpace: true,
        matchWholeWord: false
      });
```

## Current Behavior
Word online (Chrome, Edge latest versions) crashes. The same errors appear in the both console logs at time of crash:
![image](https://user-images.githubusercontent.com/57560358/80931190-1f63f500-8d86-11ea-847d-18797eb2d73f.png)

```
TypeError: Unable to get property 'charAt' of undefined or null reference
   at Anonymous function (https://c1-word-edit-15.cdn.office.net/we/s/161290137775_App_Scripts/WordEditor.box4.dll3.js:41:76)
   at wac_Agd.prototype.ftc (https://c1-word-edit-15.cdn.office.net/we/s/161290137775_App_Scripts/WordEditor.box4.dll3.js:998:58)
   at wac_u$b.prototype.Ecf (https://c1-word-edit-15.cdn.office.net/we/s/161290137775_App_Scripts/WordEditor.box4.dll1.js:2384:117)
   at Anonymous function (https://c1-officeapps-15.cdn.office.net/we/s/161290137775_App_Scripts/MicrosoftAjax.js:5:298)
   at wac_Ah.prototype.lw (https://c1-word-edit-15.cdn.office.net/we/s/161290137775_App_Scripts/WordEditor.js:1075:356)
   at Anonymous function (https://c1-officeapps-15.cdn.office.net/we/s/161290137775_App_Scripts/MicrosoftAjax.js:5:298)
   at wac_jRc.prototype.TIa (https://c1-word-edit-15.cdn.office.net/we/s/161290137775_App_Scripts/WordEditor.box4.dll2.js:281:303)
   at wac_Zja.prototype.TIa (https://c1-word-edit-15.cdn.office.net/we/s/161290137775_App_Scripts/WordEditor.js:639:73)
   at wac_3l.prototype.lw (https://c1-word-edit-15.cdn.office.net/we/s/161290137775_App_Scripts/WordEditor.js:1082:375)
   at Anonymous function (https://c1-officeapps-15.cdn.office.net/we/s/161290137775_App_Scripts/MicrosoftAjax.js:5:298)
WordEditor.js (608,425)
```
Setting `matchWildCards:false` results in proper code execution.

I am using Requirements Set 1.1.

**Comment by mscharlock** [comment]
@weshi - Do you mind having a look at this? Thanks!

**Comment by mmoore-3lc** [comment]
Hello,

Is there an update to this issue?

**Comment by mmoore-3lc** [comment]
Hello,

Is it possible to look at this issue?
