### ISSUE TITLE
Excel load(string[]) doesn't work for nested properties

### ISSUE THREAD

**Issue by nikolay-borzov** [OfficeDev/office-js#190]
## Expected Behavior

`worksheets.load(['items/id', 'items/name'])`

must have the same effect as

`worksheets.load('items/id, items/name')`

## Current Behavior

```
Excel.run(async context => {
  const worksheets = context.workbook.worksheets;

  worksheets.load(['items/id', 'items/name']);

  await context.sync();

  worksheets.items.forEach(ws => console.log(`id: ${ws.id}, name: ${ws.name}`));
});
```
Throws an error:
> PropertyNotLoaded: The property 'name' is not available. Before reading the property's value, call the load method on the containing object and call "context.sync()" on the associated request context.
> RichApi.Error: The property 'name' is not available. Before reading the property's value, call the load method on the containing object and call "context.sync()" on the associated request context.

## Steps to Reproduce, or Live Example

* Link to live example: https://gist.github.com/c63494165a7dfebd41138ac335a6b3a9

* Additional details:
  1. [Documentation](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-advanced-concepts#loading-the-properties-of-an-object) doesn't say there should be difference between string and array arguments

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: Office Online
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: MS Office 365 ProPlus
* Operating System: Windows 10
* Browser (if using Office Online): Chrome (67.0.3396.99)

## Useful logs

- [x] Console errors (see actual behavuior)

```
error_handler.js?5945:54 EXCEPTION: Uncaught (in promise): PropertyNotLoaded: The property 'name' is not available. Before reading the property's value, call the load method on the containing object and call "context.sync()" on the associated request context.
Error: The property 'name' is not available. Before reading the property's value, call the load method on the containing object and call "context.sync()" on the associated request context.
    at r.ZoneAwareError (webpack-internal:///788:992:33)
    at new r (https://appsforoffice.microsoft.com/lib/1/hosted/excel-web-16.00.js:21:257500)
    at Function.f.createPropertyNotLoadedException (https://appsforoffice.microsoft.com/lib/1/hosted/excel-web-16.00.js:21:346085)
    at f.throwIfNotLoaded (https://appsforoffice.microsoft.com/lib/1/hosted/excel-web-16.00.js:21:345989)
    at k.get [as name] (https://appsforoffice.microsoft.com/lib/1/hosted/excel-web-16.00.js:21:400726)
    at eval (webpack-internal:///1283:45:122)
    at Array.forEach (<anonymous>)
    at InitEffects.eval (webpack-internal:///1283:45:46)
    at step (webpack-internal:///3:107:23)
    at Object.eval [as next] (webpack-internal:///3:88:53)
    at fulfilled (webpack-internal:///3:78:58)
    at ZoneDelegate.invoke (webpack-internal:///788:334:26)
    at Object.onInvoke (webpack-internal:///191:275:37)
    at ZoneDelegate.invoke (webpack-internal:///788:333:32)
    at Zone.run (webpack-internal:///788:126:43)
```

**Comment by Zlatkovsky** [comment]
@nikolay-borzov , thanks for reporting this.  Let me investigate...

**Comment by lumine2008** [comment]
Hi @nikolay-borzov , You could use  `worksheets.load("items");` to load the array.

**Comment by keyur32** [comment]
Closing this as workaround provided
