### ISSUE TITLE
Error while adding DataValidationRule to Excel addin

### ISSUE THREAD

**Issue by mayankthebest** [OfficeDev/office-js#193]
When I am trying to add Data Validation to an Excel add in as explained here https://docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-data-validation , I am getting error:

```
GeneralException: An internal error has occurred.
   at Anonymous function (https://appsforoffice.microsoft.com/lib/beta/hosted/excel-win32-16.01.js:21:255173)
   at ai (https://appsforoffice.microsoft.com/lib/beta/hosted/excel-win32-16.01.js:21:198334)
   at ft (https://appsforoffice.microsoft.com/lib/beta/hosted/excel-win32-16.01.js:21:198421)
   at d (https://appsforoffice.microsoft.com/lib/beta/hosted/excel-win32-16.01.js:21:198241)
   at c (https://appsforoffice.microsoft.com/lib/beta/hosted/excel-win32-16.01.js:21:196937)
```

This does not work even for basic validation.

**Comment by JuaneloJuanelo** [comment]
please  make sure to use the template to report an issue, we need way more information in other to help you.


## Expected Behavior


## Current Behavior



## Steps to Reproduce, or Live Example



* Link to live example: ______


* Additional details:
  1. ______
  2. ______
  3. ______

## Context



## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: ______
* Host [Excel, Word, PowerPoint, etc.]: ______
* Office version number: ______
* Operating System: ______
* Browser (if using Office Online): ______

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)
