### ISSUE TITLE
Word add-in - undefined is not an object (evaluating 'OSF.DDA.RichApi.richApiMessageManager.register')

### ISSUE THREAD

**Issue by ndvbd** [OfficeDev/office-js#1936]
Hi,

My Sentry reports many users with the exception of:

`undefined is not an object (evaluating 'OSF.DDA.RichApi.richApiMessageManager.register')`

this exception is being thrown in MS file: /lib/1/hosted/word-ios-16.00.js at line 26:309733

`{snip} r,e)}));case 5:return OSF.DDA.RichApi.richApiMessageManager.register(r);case 13:return Z.promisify((function(e){return Office.context.docume {snip}`

This affects many users. Can someone in MS have a look at it?

**Comment by alison-mk** [comment]
Hi @ndvbd, thank you for submitting this issue! I've assigned it to the engineering team who will be able to provide you with more information or help resolve the issue. 

Cheers,
Alison

**Comment by jake-chambers** [comment]
I also am having this issue

**Comment by jankrynauw** [comment]
Also having the same issue - referenced the details in #3582

**Comment by gaskaj** [comment]
Same issue as @jankrynauw any resolution?

```Office.context.ui.messageParent("SAMPLE", { targetOrigin: "*" });```

This did not resolve issue either

![Screenshot 2024-04-06 at 1 24 20 PM](https://github.com/OfficeDev/office-js/assets/833726/915cd118-34d5-4d0d-b33f-7b4b7aa46b9f)

**Comment by svashisth07** [comment]
I am also facing same issue

`TypeError: undefined is not an object (evaluating 'OSF.DDA.RichApi.richApiMessageManager.register')
  at None (/lib/1.1/hosted/excel-mac-16.00.js:25:357783)
  at None (/lib/1.1/hosted/excel-mac-16.00.js:25:1445824)`

**Comment by jaiswalshubh1** [comment]
Hi @ndvbd ,

Found similar issue https://github.com/OfficeDev/office-js/issues/6344 which is resolved. @ndvbd can you please confirm that issue still persist as fix is done for win32?

cc: @kustonaut 

Thanks!
Shubham Jaiswal

**Comment by jaiswalshubh1** [comment]
Hi @ndvbd ,

We are waiting for your response as issue has already fixed, I am closing this issue, please feel free to open fresh bug if you get same issue.

CC: @kustonaut 

Thanks!
Shubham Jaiswal
