### ISSUE TITLE
Reapplying an excel table's sort causes a general exception when there's two workbooks open

### ISSUE THREAD

**Issue by Stepan-Valkov** [OfficeDev/office-js#2676]
## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 2205, build 15225.20288
* Operating System: Windows 10
* Browser (if using Office on the web): n/a
 
## Expected behavior
Table.sort.reapply() call reapplies sorting as expected even if there are several workbooks open.

## Current behavior
When table.sort.reapply() is called for a table in a workbook that is not currently active, the following exception is thrown:
`GeneralException RichApi.Error: There was an internal error while processing the request.`
I expected it to work normally (to reapply the sort)

## Steps to reproduce
1. Create an excel table with any sorting 
2. Open another workbook
3. Call table.sort.reapply() for your table while the focus is in the second workbook's window (e.g. using a delay like it's done in the gist below)

## Link to live example(s)
Gist link: https://gist.github.com/Stepan-Valkov/6e5ed77441b469a56613af4296a19765

# Provide additional details

Note that the second button has a built-in delay which should be enough for the tester to move focus from the workbook in question to an empty one

## Context
Our excel add-in updates the data contained in excel tables constantly and we want to be able to sort it periodically, even if several workbooks are open

## Useful logs
The exception isn't very verbose, but here's the stack trace:
`GeneralException RichApi.Error: There was an internal error while processing the request.
    at new n (https://appsforoffice.microsoft.com/lib/1/hosted/excel-win32-16.01.js:25:240171)
    at i.processRequestExecutorResponseMessage (https://appsforoffice.microsoft.com/lib/1/hosted/excel-win32-16.01.js:25:304337)
    at https://appsforoffice.microsoft.com/lib/1/hosted/excel-win32-16.01.js:25:302400`

**Comment by keyur32** [comment]
sorry was on vacation and didn't see this. Assigning to @yaweizhu-henson  who drives Excel APIs. thx.

**Comment by SiruiSun-MSFT** [comment]
Hi @Stepan-Valkov , sorry for delay response. After investigation, it turned out that the bug is in Excel side when reapplying an excel table's sort (bug id: 6244801). We have contact Excel team and they are actively working on it. Unfortunately, I don't have a timeline to share at this point, but I will keep updated in this thread. Thanks!

**Comment by chandpravandan** [comment]
@Stepan-Valkov we are unable to repro this on the latest version of Excel, can you please confirm whether this repro's for you

**Comment by Stepan-Valkov** [comment]
Seems like I cannot reproduce it anymore either (Excel for Microsoft 365 MSO (Version 2510 Build 16.0.19328.20266)). Unfortunately I can't run the attached gist due to changes in security policy, but in the actual add-in we no longer log the message that we put there in case someone runs into this specific issue.

Edit: another change to the reported environment is the OS (now it's windows 11) - though it should not matter much

**Comment by chandpravandan** [comment]
@Stepan-Valkov sure, I think we can close this since we are not able to repro, please feel free to reach out if this scenario repro's
