### ISSUE TITLE
Outlook Addin button not working on OWA when email matches contextual string

### ISSUE THREAD

**Issue by gianluca-venturini** [OfficeDev/office-js#2798]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Outlook web
* Office version number: Current Office on the web
* Operating System: Mac OSX
* Browser (if using Office on the web): Chrome
 
## Expected behavior
- I created an addin that activates in the following two cases:
1. When a contextual string matches (the string is "This is a test")
2. When the user press the button "Test me", the button appears in the addin menu
- Every time I press "Test me" button on the addin menu, the addin is loaded.

## Current behavior

- Select an email that contains the text "This is a test", that matches the contextual addin regex.
- The first time I press "Test me" button on the addin menu, I see the following error in console
```
owa.Addins.js:2 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'filter')
    at owa.Addins.js:2:1008746
    at owa.Addins.js:2:1008775
    at Array.forEach (<anonymous>)
    at st (owa.Addins.js:2:1008513)
    at ct (owa.Addins.js:2:1010594)
    at It (owa.Addins.js:2:1013484)
    at async _t (owa.Addins.js:2:1014557)
    at async owa.Addins.js:2:1022002
```
- Every time I open any addin (clicking on the addin button) from that moment on, the addin is not working (spins for few seconds and then gives the "something went wrong" error).
- You can see the behavior in this video: https://www.loom.com/share/5ea07756255745e284884e1e5ab36e12. In the video you can see that the first time I launch the addin, from an email that doesn't match the contextual addin regex, the addin works correctly. The second time I launch the addin from an email that matches the contextual regex, you can see the console error. You can see that every time I launch the addin after that, it always fails to load.

## Steps to reproduce

- side-load the test addin I provided below (I provided the XML manifest).
- Select an email that contains the text "This is a test", that matches the contextual addin regex.
- The first time I press "Test me" button on the addin menu, the addin activates and I see the following error in console.
```
owa.Addins.js:2 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'filter')
    at owa.Addins.js:2:1008746
    at owa.Addins.js:2:1008775
    at Array.forEach (<anonymous>)
    at st (owa.Addins.js:2:1008513)
    at ct (owa.Addins.js:2:1010594)
    at It (owa.Addins.js:2:1013484)
    at async _t (owa.Addins.js:2:1014557)
    at async owa.Addins.js:2:1022002
```
- Every time I open any addin from that moment on, the addin is not working (spins for few seconds and then gives the "something went wrong" error).
- You can see the behavior in this video: https://www.loom.com/share/5ea07756255745e284884e1e5ab36e12

# Provide additional details

- It only happens on emails that match the contextual addin text "This is a test".
- It doesn't happen if I remove this part from the manifest:
```
           <ExtensionPoint xsi:type="DetectedEntity">
                <Label resid="s8.RetrieveButton.Label"/>
                <SourceLocation resid="s8.retrieveUrl"/>
                <Rule xsi:type="RuleCollection" Mode="And">
                    <Rule xsi:type="ItemIs" ItemType="Message"/>
                    <Rule xsi:type="RuleCollection" Mode="Or">
                        <Rule xsi:type="ItemHasRegularExpressionMatch" RegExName="s8.retrieveText.0" RegExValue="This is a test" IgnoreCase="false" PropertyName="BodyAsPlaintext" Highlight="all"/>
                    </Rule>
                </Rule>
            </ExtensionPoint>
```
- The issue started recently, I've been using this type of addins on OWA in the past few years and never noticed the issue.

## Context

The issue affects any OWA Outlook addin that contains a contextual regex match in its manifest and a button. The issue started somewhat recently because I've tested my addin in the past years on OWA and it always worked correctly.

## Useful logs

- [x] Console errors
```
owa.Addins.js:2 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'filter')
    at owa.Addins.js:2:1008746
    at owa.Addins.js:2:1008775
    at Array.forEach (<anonymous>)
    at st (owa.Addins.js:2:1008513)
    at ct (owa.Addins.js:2:1010594)
    at It (owa.Addins.js:2:1013484)
    at async _t (owa.Addins.js:2:1014557)
    at async owa.Addins.js:2:1022002
```
- [x] Video: https://www.loom.com/share/5ea07756255745e284884e1e5ab36e12
- [x] Test file: this is the addin manifest that I used for my tests:
```
<?xml version="1.0" encoding="UTF-8"?>
<OfficeApp xmlns="http://schemas.microsoft.com/office/appforoffice/1.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:bt="http://schemas.microsoft.com/office/officeappbasictypes/1.0" xmlns:mailappor="http://schemas.microsoft.com/office/mailappversionoverrides/1.0" xsi:type="MailApp">
<Id>1dda6b13-d03b-4db1-8f5e-93eedafa2aaa</Id>
<Version>1.0.0</Version>
<ProviderName>Test</ProviderName>
<DefaultLocale>en-US</DefaultLocale>
<DisplayName DefaultValue="Test me"/>
<Description DefaultValue="Test me."/>
<IconUrl DefaultValue="https://uploads.codesandbox.io/uploads/user/77daef40-23cd-4502-9014-0cd1830734f3/O1p--output-onlinepngtools+(34).png"/>
<HighResolutionIconUrl DefaultValue="https://uploads.codesandbox.io/uploads/user/77daef40-23cd-4502-9014-0cd1830734f3/O1p--output-onlinepngtools+(34).png"/>
<SupportUrl DefaultValue="https://staging.on.stellarite.io/oa/addin-legacy.html"/>
<AppDomains>
    <AppDomain>https://staging.on.stellarite.io/oa/addin-legacy.html</AppDomain>
</AppDomains>


<Hosts>
    <Host Name="Mailbox"/>
</Hosts>
<Requirements>
    <Sets>
        <Set Name="Mailbox" MinVersion="1.1"/>
    </Sets>
</Requirements>
<FormSettings>
    <Form xsi:type="ItemRead">
        <DesktopSettings>
            <SourceLocation DefaultValue="https://https-everywhere.badssl.com/"/>
            <RequestedHeight>450</RequestedHeight>
        </DesktopSettings>
    </Form>
</FormSettings>
<Permissions>ReadWriteMailbox</Permissions> 
<Rule xsi:type="RuleCollection" Mode="And">
    <Rule xsi:type="ItemIs" ItemType="Message" FormType="Read"/>
    <Rule xsi:type="ItemHasRegularExpressionMatch" RegExName="notUsed" RegExValue=".*" IgnoreCase="true" PropertyName="BodyAsPlaintext"/>
</Rule>
<DisableEntityHighlighting>false</DisableEntityHighlighting>


<VersionOverrides xmlns="http://schemas.microsoft.com/office/mailappversionoverrides" xsi:type="VersionOverridesV1_0">
<VersionOverrides xmlns="http://schemas.microsoft.com/office/mailappversionoverrides/1.1" xsi:type="VersionOverridesV1_1">
<Requirements>
    <bt:Sets>
        <bt:Set Name="Mailbox" MinVersion="1.1"/>
    </bt:Sets>
</Requirements>
<Hosts>
    <Host xsi:type="MailHost">
        <DesktopFormFactor>
            <SupportsSharedFolders>true</SupportsSharedFolders>
            <ExtensionPoint xsi:type="MessageReadCommandSurface">
                <OfficeTab id="TabDefault">
                    <Group id="msgReadGroup">
                        <Label resid="s8.GroupLabel"/>
                        <Control xsi:type="Button" id="s8.RetrieveButton">
                            <Label resid="s8.RetrieveButton.Label"/>
                            <Supertip>
                                <Title resid="s8.RetrieveButton.Label"/>
                                <Description resid="s8.RetrieveButton.Tooltip"/>
                            </Supertip>
                            <Icon>
                                <bt:Image size="16" resid="s8.RetrieveButton.Icon.16x16"/>
                                <bt:Image size="32" resid="s8.RetrieveButton.Icon.32x32"/>
                                <bt:Image size="80" resid="s8.RetrieveButton.Icon.80x80"/>
                            </Icon>
                            <Action xsi:type="ShowTaskpane">
                                <SourceLocation resid="s8.retrieveUrl"/>
                            </Action>
                        </Control>
                    </Group>
                </OfficeTab>
            </ExtensionPoint>
            <ExtensionPoint xsi:type="DetectedEntity">
                <Label resid="s8.RetrieveButton.Label"/>
                <SourceLocation resid="s8.retrieveUrl"/>
                <Rule xsi:type="RuleCollection" Mode="And">
                    <Rule xsi:type="ItemIs" ItemType="Message"/>
                    <Rule xsi:type="RuleCollection" Mode="Or">
                        <Rule xsi:type="ItemHasRegularExpressionMatch" RegExName="s8.retrieveText.0" RegExValue="This is a test" IgnoreCase="false" PropertyName="BodyAsPlaintext" Highlight="all"/>
                    </Rule>
                </Rule>
            </ExtensionPoint>
        </DesktopFormFactor>
    </Host>
</Hosts>
<Resources>
    <bt:Images>
        <bt:Image id="s8.RetrieveButton.Icon.16x16" DefaultValue="https://uploads.codesandbox.io/uploads/user/77daef40-23cd-4502-9014-0cd1830734f3/O1p--output-onlinepngtools+(34).png"/>
        <bt:Image id="s8.RetrieveButton.Icon.32x32" DefaultValue="https://uploads.codesandbox.io/uploads/user/77daef40-23cd-4502-9014-0cd1830734f3/O1p--output-onlinepngtools+(34).png"/>
        <bt:Image id="s8.RetrieveButton.Icon.80x80" DefaultValue="https://uploads.codesandbox.io/uploads/user/77daef40-23cd-4502-9014-0cd1830734f3/O1p--output-onlinepngtools+(34).png"/>
    </bt:Images>
    <bt:Urls>
        <bt:Url id="s8.retrieveUrl" DefaultValue="https://staging.on.stellarite.io/oa/addin-legacy.html"/>
    </bt:Urls>
    <bt:ShortStrings>
        <bt:String id="s8.GroupLabel" DefaultValue="Test me"/>
        <bt:String id="s8.RetrieveButton.Label" DefaultValue="Test me"/>
    </bt:ShortStrings>
    <bt:LongStrings>
        <bt:String id="s8.RetrieveButton.Tooltip" DefaultValue="Test me."/>
    </bt:LongStrings>
</Resources>
</VersionOverrides>
</VersionOverrides>
            
</OfficeApp>
```

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by exextoc** [comment]
Thanks for reporting this issue. We have put it in our backlog. Unfortunately, we don't have any timelines to share at this point. Internal tracking id: 169197

**Comment by exextoc** [comment]
@gianluca-venturini  We have fixed the bug and the fix should be available in next build. When an updated build is available depends on the release channel a customer is on. Can you check and confirm the fix?

**Comment by ghost** [comment]
This issue has been automatically marked as stale because it is marked as needing author feedback but has not had any activity for **4 days**. It will be closed if no further activity occurs **within 3 days of this comment**. Thank you for your interest in Office Add-ins!
