### ISSUE TITLE
File insertion in Word fails with error ooxmlIsMalformated

### ISSUE THREAD

**Issue by FranCerrada** [OfficeDev/office-js#3270]
I encountered an issue when inserting a file in base 64 in Word. When trying to insert anything we get the following error:

```
RichApi.Error: ooxmlIsMalformated
    at new n (https://appsforoffice.microsoft.com/lib/beta/hosted/word-web-16.00.js:25:330439)
    at o.processRequestExecutorResponseMessage (https://appsforoffice.microsoft.com/lib/beta/hosted/word-web-16.00.js:25:394605)
    at https://appsforoffice.microsoft.com/lib/beta/hosted/word-web-16.00.js:25:392668
```

This is the code in place to insert the file:
```
 return Word.run((context) => {
      const range = context.document.getSelection();
      range.insertFileFromBase64(base64file, Word.InsertLocation.replace);
      return context.sync();
    })
```
It also fails when using other insert location strategies, such as end or start. I've also ensured that the base64file is valid, by copying the content to a new file, saving it as .doc, and opening it in Word.

I am using the beta channel (`https://appsforoffice.microsoft.com/lib/beta/hosted/office.js`), but I've also tried on the release channel (`https://appsforoffice.microsoft.com/lib/1/hosted/office.js`) and it is also failing.

This was not failing a couple of weeks ago, so I am afraid something has recently changed that has broken this functionality. 

Worth mentioning that is working in Office for Mac.

## Your Environment
Platform: Office Online
Host: Word
Operating System: Windows 10
Browser: Chrome
 
## Expected behavior
The file will be inserted into the document.

## Current behavior
Insertion fails with the error message `ooxmlIsMalformated`

## Steps to reproduce
Try to insert a file in base64 format into the Word application using office-js beta or release channel

**Comment by penglongzhaochina** [comment]
Thanks for reporting this issue.  

It has been put on our backlog<Bug#7765252> for internal track. We will keep track of this issue and let you know if there are any updates.

**Comment by JinghuiMS** [comment]
Thanks for reporting this issue in time. Sorry for the inconvenience caused to you. These two days we are actively working on this. The fix should be available to all of you. Please double check it in your environment after clearing your browser cache. 
Please let us know if you have any further questions. Thank you all again!

**Comment by ghost** [comment]
This issue has been automatically marked as stale because it is marked as needing author feedback but has not had any activity for **4 days**. It will be closed if no further activity occurs **within 3 days of this comment**. Thank you for your interest in Office Add-ins!

**Comment by Mukhammadsaid19** [comment]
Experiencing the same issue. Just a mere replacement with the same ooxml of the document throws ooxmlIsMalformated exception. Steps to reproduce:

```
return Word.run(async (context) => {
      const body = context.document.body;
      const bodyOOXML = body.getOoxml();
      await context.sync();

      // Queue a command to replaceOOXML
      body.insertOoxml(bodyOOXML.value, "Replace");
      await context.sync();
    });
```

Throws a `ooxmlIsMalformated` error in Office Online. It works fine in Windows or Mac Word.

**Comment by SedVrak** [comment]
I also had an error in Word Online.
I am using the beta version _https://appsforoffice.microsoft.com/lib/beta/hosted/office.js_.
Everything works fine locally in Word on Windows 11.
Has anyone found a solution to the problem? 
My result:
```
RichApi.Error: ooxmlIsMalformated
    at new n (word-web-16.00.js:25:332681)
    at o.processRequestExecutorResponseMessage (word-web-16.00.js:25:396847)
    at word-web-16.00.js:25:394910
```
