### ISSUE TITLE
Slow network causes "Office.js has not fully loaded. Your app must call "Office.onReady()" as part of it's loading sequence (or set the "Office.initialize" function). If your app has this functionality, try reloading this page."

### ISSUE THREAD

**Issue by GlaserIngo** [OfficeDev/office-js#3330]
# Provide required information needed to triage your issue
I have developed a Word AddIn using React. I used the yeoman generator to setup the application. During development, I never had an issue on any platform (Windows, Mac, Web) testing the AddIn locally.

Now, I wanted to let external people test the AddIn. Therefore, I used the side loading process according to the documentation of Microsoft. The main difference to the local deployment is obviously the fact, that the AddIn is hosted on Azure. Thereby, I received the following error:
![Bildschirmfoto 2023-05-03 um 12 48 27](https://user-images.githubusercontent.com/5706289/235896335-d5d6a3ea-6800-4dcf-b814-875e7d62b5ba.png)

Obviously I am using the onReady function. I also tried to avoid using ES6 syntax as well as use an empty .initialize function as this was stated in other threads. Neither worked. As I was trying to load the AddIn in the browser at the clients machine, that showed the error, I noticed that the Webapp was loading quite slow. As a result I did some testing and figured the circumstances causing that error:

It does not matter how long it takes to actually fire the request to load the application. But, if I delay the response (not server side, I actually delay the receiving of the response artificially on the client), I get this error. The delay must be around 7000-8000ms to cause the error. I could replicate this one Windows as well as Mac with the latest Office 365 Word Desktop version. 

So we can clearly identify that the cause for this error is a slow network connection.

Is there anything I can do to avoid that error? It basically makes it impossible for many users to use Word AddIns. 

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: Mac, PC Desktop with Windows 11, Surface Pro with Windows 11
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: Mac 16.72 (23040900), Windows Office 365 LTS
* Operating System: Windows 11, macOS Monterey Version 12.5
* Browser (if using Office on the web): ______

It really does not matter which version of Word or operating system I use to cause this error.
 
## Expected behavior
The AddIn waits for the request to be served and actually starts the application without throwing a weird error that does not make sense as we utilize the .onReady() function.

## Current behavior
The AddIn shows a blank page and the console shows the following error: Office.js has not fully loaded. Your app must call "Office.onReady()" as part of it's loading sequence (or set the "Office.initialize" function). If your app has this functionality, try reloading this page.

## Steps to reproduce
1. Sideload a Word AddIn on any platform (Mac or Windows). Therefore follow either the these steps https://learn.microsoft.com/en-us/office/dev/add-ins/testing/sideload-an-office-add-in-on-mac or those https://learn.microsoft.com/en-us/office/dev/add-ins/testing/create-a-network-shared-folder-catalog-for-task-pane-and-content-add-ins
2. Artificially slow down your network before opening the AddIn. Preferably use either Fiddler on Windows (https://www.telerik.com/fiddler) to slow down the reception of the response (see here https://blog.testproject.io/2021/09/27/simulating-slow-network-connection-for-testing/) or use Network Link Conditioner (https://developer.apple.com/download/more/?q=Additional%20Tools) on Mac.
3. Load the AddIn and observe the error.

## Link to live example(s)
You can use any Word AddIn that was generated with Yeoman. Perhaps, the AddIn needs to have a certain size in order to cause that error.

## Context
I try to let the AddIn run at customers which is obviously not possible if many of them receive this error due to not the best network connection.

Thanks for your help! I figured the issue was already reported a few times. But no solution is apparent.

**Comment by JinghuiMS** [comment]
@jayrathi Any ideas on it? Thanks!

**Comment by GlaserIngo** [comment]
I really believe many others should have that issue as well. At least, I did found similar issues here on GitHub and a few reports via Google search.

**Comment by laurence-splendr** [comment]
Seems like we are having the same issue right now. Exactly as described except we're using Angular instead of React. We're transpiling down to ES5, so any arrow functions have been changed appropriately. We're using both empty Office.initialize() and call Office.onReady(). We're able to use this locally no problem.

**Comment by GlaserIngo** [comment]
Any news on that?

**Comment by codervishal81** [comment]
We are having the same issue. We are using Angular. And as mentioned in the start of the post, in debug tool if we set network throttling as "Slow 3G" then it is easily reproduced.

Please let us know the solution for this.

**Comment by demkantor** [comment]
same error message on an outlook addin made with react. works for most everyone outside of desktop on mac for just a handful of people - works just fine in multiple browsers for those same people. Development isnt fully complete but worry once it is released this issue will show up more widespread.
Any updates on this? Any work around to complete to negate the issue found? would it be wise to import the npm package and use this instead of the CDN? Should we shift gears and move to graph api instead?

**Comment by IgorKennyPavlov** [comment]
Same problem with React-based Outlook add-in. The workaround through assigning an empty function to Office.initialize before calling Office.onReady didn't help.

**Comment by KaranLala** [comment]
Same problem here. Content Add-in built on React generated with Yeoman. 
I was able to solve this by greatly reducing the file size of taskpane.js. (Even though mine is a content add-in it started out as a task pane). 

Initially the file size of taskpane.js in production was ~12MB because of fluentui (is it not tree-shaking?). After removing fluentui throughout the app, the taskpane.js file is now at ~145KB. It now works even with "Slow 3G" enabled, so while there is still an underlying issue that needs to be fixed in Office.js, for most practical scenarios this solution works for me.

**Comment by iraviguggilam** [comment]
is there any update on this ?
We are developing the Outlook Addin using Angular ( serve with nodejs ). Side loading is working some times and giving error some times.

**Comment by nsusr3** [comment]
We face the same problem. Our outlook add in is made with react framework and sometimes when we launch the add-in we get the same error. We try all the above solutions and nothing works. Please give some suggestions.

**Comment by vichanda** [comment]
I too facing same issue. It was working in my local machine. When deployed the code to Amazon S3 server through pipeline, it started showing above error. We spent two days to resolved the issue. Later I moved back to local machine, it is showing same issue which was working previously.

Please help if somebody has any solution.

**Comment by q-mariofialho** [comment]
Any updates on this.  I am trying to run this locally and I am getting the same error.  
Error: Office.js has not fully loaded. Your app must call "Office.onReady()" as part of it's loading sequence (or set the "Office.initialize" function). If your app has this functionality, try reloading this page.  
    at office.js:76:32102
    at c (office.js:76:4752)

Any help would be greatly appreciated!!
My Code:
taskpane.ts
```
/*
 * Copyright (c) Microsoft Corporation. All rights reserved. Licensed under the MIT license.
 * See LICENSE in the project root for license information.
 */

// eslint-disable-next-line no-redeclare
/* global document, Office, Word */
import nlp from "compromise";
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import * as natural from "natural";
import { sendToChatGPT } from "../api/api";

const keyValueTable: { [key: string]: string } = {};
// eslint-disable-next-line @typescript-eslint/no-unused-vars
let tokenCounter = 0;

Office.onReady((info: { host: unknown }) => {
  if (info.host === Office.HostType.Word) {
    document.getElementById("process-document").onclick = processDocument;
    document.getElementById("send-to-chatgpt").onclick = async () => {
      try {
        const text = await getDocumentText();
        const response = await sendToChatGPT(text);
        await acceptResponse(response);
      } catch (error) {
        // eslint-disable-next-line no-undef
        console.error("Error in send-to-chatgpt button click:", error);
        // eslint-disable-next-line no-undef
        alert(`Error in send-to-chatgpt button click: ${error}`);
      }
    };
    document.getElementById("accept-response").onclick = async () => {
      try {
        const text = await getDocumentText();
        await acceptResponse(text);
      } catch (error) {
        // eslint-disable-next-line no-undef
        console.error("Error in accept-response button click:", error);
        // eslint-disable-next-line no-undef
        alert(`Error in accept-response button click: ${error}`);
      }
    };
  }
});

const tokenizeSensitiveInfo = (text: string): string => {
  const doc = nlp(text);

  // Example patterns for sensitive information
  const sensitivePatterns = [
    { type: "Name", pattern: doc.people().out("array") },
    { type: "Address", pattern: doc.match("#Address").out("array") },
    { type: "Phone", pattern: doc.match("#PhoneNumber").out("array") },
    { type: "SSAN", pattern: /\b\d{3}-\d{2}-\d{4}\b/g },
    { type: "Product", pattern: doc.match("#Product").out("array") },
    { type: "Company", pattern: doc.match("#Company").out("array") },
    { type: "URL", pattern: doc.match("#Url").out("array") },
  ];

  sensitivePatterns.forEach((pattern) => {
    const matches = Array.isArray(pattern.pattern) ? pattern.pattern : text.match(pattern.pattern);
    if (matches) {
      matches.forEach((match) => {
        tokenCounter++;
        const token = "[['${pattern.type}' '${tokenCounter}']]";
        keyValueTable[token] = match;
        text = text.replace(new RegExp(match, "g"), token);
      });
    }
  });

  return text;
};

export async function processDocument() {
  try {
    await Word.run(async (context) => {
      const body = context.document.body;
      body.load("text");
      await context.sync();

      const tokenizedText = tokenizeSensitiveInfo(body.text);
      body.clear();
      body.insertText(tokenizedText, Word.InsertLocation.start);

      await context.sync();
    });
  } catch (error) {
    // eslint-disable-next-line no-undef
    console.error("Error processing document:", error);
    // eslint-disable-next-line no-undef
    alert("Error processing document: ${error}");
  }
}

export async function acceptResponse(chatGptResponse: string) {
  try {
    await Word.run(async (context) => {
      const body = context.document.body;
      let updatedText = chatGptResponse;

      for (const token in keyValueTable) {
        const sensitiveInfo = keyValueTable[token];
        updatedText = updatedText.replace(new RegExp(token, 'g'), sensitiveInfo);
      }

      body.clear();
      body.insertText(updatedText, Word.InsertLocation.start);
      await context.sync();
    });
  } catch (error) {
    // eslint-disable-next-line no-undef
    console.error("Error accepting response:", error);
    // eslint-disable-next-line no-undef
    alert("Error accepting response: ${error}");
  }
}

export async function getDocumentText() {
  try {
    return await Word.run(async (context) => {
      const body = context.document.body;
      body.load("text");
      await context.sync();
      return body.text;
    });
  } catch (error) {
    // eslint-disable-next-line no-undef
    console.error("Error getting document text:", error);
    // eslint-disable-next-line no-undef
    alert("Error getting document text: ${error}");
    return "";
  }
}

```
Error;
<img width="948" alt="image" src="https://github.com/user-attachments/assets/40de847e-1bcc-47f8-b45a-a9ccf2dba502">

**Comment by shaun-pendrigh** [comment]
I urgently need a solution or at least a workaround for this issue. Locally I have no problems. But my test and production environments are deployed on Azure and I sometimes simply cannot get the Add-in to load despite refreshing 20 or more times. This completely prevents me from being able to complete final testing and will also affect any of my customers that do not have a fast connection to the Azure servers.

**Comment by Mario4272** [comment]
Hey @shaun-pendrigh I wound up recreating the yo office package as JavaScript vs typescript and it works much better.  could be a work around until the TS issues worked out. Just a thought.

**Comment by shaun-pendrigh** [comment]
Thanks @Mario4272. I was thinking about trying to package the JavaScript and perhaps minify it. The code has got fairly large now so possibly it is taking too long to load it and it reaches some sort of timeout on the Office side. Will give it a try.

**Comment by stanislasgrare** [comment]
Same problem here. Excel add-in with React. The taskpane always shows up (on windows at least, on mac almost every time it does not load anything ) but When I open a dialog window, I would say that 60 percent of the time it loads correctly. Otherwise I get the exact same error.  I have used OnReady() , I have followed the official tutorial as well.

**Comment by shaun-pendrigh** [comment]
So I managed to work around my specific problem, but reading the posts on this issue I doubt it would be everyone's solution.

As my code has grown the number of separate (TypeScript) class files I has has increased exponentially. I think the "timeout" that is occurring is while office waits for my code to load. I created a dynamic import from the OnReady() call to the first resource that get's used and the error no longer occurs. I presume this results in the office initialization completing before this "timeout".

**Comment by Mario4272** [comment]
@shaun-pendrigh - Got a code sample? :-) I ended up switching to JS and things work perfectly.  Not the optimum solution, but a workaround.

**Comment by shaun-pendrigh** [comment]
@Mario4272 code used to be something like this:

```
import { MyClass } from "./path/my-class.js";

void Office.onReady(async (info) => {
  if (info.host === Office.HostType.Excel) {
    await new MyClass().initialize();
  }
});

```
MyClass had a bunch of imports, which in turn had further imports and so on.

Changed to:

```
void Office.onReady((info) => {
    if (info.host === Office.HostType.Excel) {
        void import("./path/taskpane-temp.js").then((taskpaneTemp) => {
            void taskpaneTemp.officeOnReady();
        });
    }
});
```

taskpaneTemp then has the actual imports to the rest of the application. Hope it makes sense. I just mocked this up as the actual code is much more complex.

**Comment by Mario4272** [comment]
@shaun-pendrigh - Awesome mate!  Great work around!!  That should help some folks including me.

**Comment by GlaserIngo** [comment]
> Same problem here. Content Add-in built on React generated with Yeoman. I was able to solve this by greatly reducing the file size of taskpane.js. (Even though mine is a content add-in it started out as a task pane).
> 
> Initially the file size of taskpane.js in production was ~12MB because of fluentui (is it not tree-shaking?). After removing fluentui throughout the app, the taskpane.js file is now at ~145KB. It now works even with "Slow 3G" enabled, so while there is still an underlying issue that needs to be fixed in Office.js, for most practical scenarios this solution works for me.

I also use fluentui and had the same issue. I worked a bit on the minimization etc., and now it's working at least more often. So this is definitely related.

**Comment by stanislasgrare** [comment]
> > Same problem here. Content Add-in built on React generated with Yeoman. I was able to solve this by greatly reducing the file size of taskpane.js. (Even though mine is a content add-in it started out as a task pane).
> > Initially the file size of taskpane.js in production was ~12MB because of fluentui (is it not tree-shaking?). After removing fluentui throughout the app, the taskpane.js file is now at ~145KB. It now works even with "Slow 3G" enabled, so while there is still an underlying issue that needs to be fixed in Office.js, for most practical scenarios this solution works for me.
> 
> I also use fluentui and had the same issue. I worked a bit on the minimization etc., and now it's working at least more often. So this is definitely related.

i am using FluentUi aswell. the thing is that my taskpane is way more complex that my dialog. the taskpane always shows up but the dialog (contains two tiny fluentUI buttons) shows up like 30 percent of the time. the rest of the time i get this error.

**Comment by JinghuiMS** [comment]
hi Area experts @jayrathi @jipyua,
 could you help take a look? Thanks very much.

**Comment by gergzk** [comment]
Hi all, 
The error in question (feel free to look at the source, search for the error, and follow up to the top of the function) is coming when an add-in is loading a file (eg: your host-platform file, like excel-web-xxx.js, or your strings file). This is done by code that brings in the file and performs a number of attempts to download. 

The argument callback is called with true/false by the waitForFunction function based on whether the dependent file is downloaded. A number of attempts are made before giving up and calling back with false. 

I have not been able to repro this (including with setting an 8s latency). If you're able to (and thank you for all the investigations above), can you see if you are running into multiple failures to download (check the if/else if/else context in waitForFunction) and/or which file(s) are failing (should be able to see this in dev tools).

**Comment by truchonh** [comment]
We have a number of users experiencing this issue, all of them using some version of Outlook Classic on Windows 10/11. I just had a meeting with one of them that is on "Microsoft Outlook 2019 MSO (16.0.10415.20025) 32bit".

Locally, using "Microsoft® Outlook® for Microsoft 365 MSO (Version 2501 Build 16.0.18429.20044) 64-bit", I can indeed reproduce the issue by opening the debugger and setting the network throttling to 3g. Office.js seems to incorrectly give up even tho not a single network error happened. The js bundle of our app just took a long time to load with the throttling.

Most interestingly, in the office.js lib code, I can change the arguments of the "waitForFunction" call where the exception is thrown to retry 4000 times instead of 400 and the add-in loads every time, even with heavy network throttling. In effect, this changes the timeout from 20 seconds (400 * 50ms) to 3min 20s. In practice it can be a bit shorter, but 20 seconds seems really fast considering that Office users often sit in big offices with very restrictive network management or slow and overloaded vpn networks when working from home.

Any reason why the lib gives up so quick ?

Your feedback would be greatly appreciated.

**Comment by mukund-9652** [comment]
Has anyone found a solution for this or analyzed any minimum bandwidth requirement or network speed that Office.Js loads without facing this issue? This issue occurs when 50+ people are connected to a single network and the network speed < 5mbps.

**Comment by q-mariofialho** [comment]
Yeah I think the solution is, if I remember correctly, to check to be sure the Office.js file is fully loaded before proceeding?  See here.

https://github.com/OfficeDev/office-js/issues/3330#issuecomment-2284190863

**Comment by mectrojohnny** [comment]
The Add-in works perfectly in a browser (Chrome/Edge) but shows a blank screen or "Office.js has not fully loaded" error in Word Desktop. Root Cause: Word Desktop (especially on older Windows builds or specific enterprise channels) often uses the Internet Explorer 11 (Trident) webview engine instead of Edge WebView2.

IE11 does not support ES6 Modules (<script type="module">).
IE11 does not support React 18's createRoot API.
IE11 does not support modern CSS or the fetch API.
Libraries like Fluent UI v9 are incompatible with IE11.
The Fix (Vite + React):

Install Legacy Support: npm install -D @vitejs/plugin-legacy terser npm install whatwg-fetch (for API calls)

Downgrade React Entry Point (
main.jsx
): Switch from ReactDOM.createRoot to ReactDOM.render:

Build & Preview: The standard vite dev server does NOT support IE11. You must build the production assets and serve them: npm run build npm run preview

**Comment by kbrilla** [comment]
For those following this thread — we've compiled a community open letter to Microsoft 
based on a systematic analysis of all 6,200+ issues in this repository. It documents 
patterns of silent breaking changes, auto-closed bugs, platform fragmentation, and the 
financial/reputation impact on ISVs and developers.

If any of this resonates with your experience, your voice would strengthen the message: 
[[link to open letter issue]](https://github.com/OfficeDev/office-js/issues/6513)

This is entirely voluntary — we just wanted to make sure affected developers are aware.
