### ISSUE TITLE
[Excel Online] workbook.names.add doesn't work with escaped strings

### ISSUE THREAD

**Issue by MitchellNZ** [OfficeDev/office-js#3770]
## Description ##
When trying to store escaped strings in a workbook level range name in Excel Online, it throws an error.
**The exact same code works fine in Excel for desktop on Windows.**

The following code gives an error when running in Excel Online:
```JavaScript
await Excel.run(async (context) => {
    context.workbook.names.add("Test_Range", "Hello \"Excel\" world!");
    await context.sync();
});
```
It still fails when trying variations of the `...add` line such as:
```JavaScript
context.workbook.names.add('Test_Range', 'Hello "Excel" world!');
```

Giving the following error:
```
...
code: "InvalidArgument"
message: "The argument is invalid or missing or has an incorrect format."
...
```
## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: **Office on the web**
* Host [Excel, Word, PowerPoint, etc.]: **Excel**
* Office version number: **Build 16.0.17016.42304**
* Operating System: **Windows**
* Browser (if using Office on the web): **Chrome & Edge** 
 
## Expected behavior

Expect the code to work, as it does on Excel for desktop on Windows.

## Current behavior

An error is thrown.

## Steps to reproduce

1. Open the **ScriptLab** addin.
2. Copy/paste the failing code into the **Run** method **in Excel for Web**.
```JavaScript
await Excel.run(async (context) => {
    context.workbook.names.add("Test_Range", "Hello \"Excel\" world!");
    await context.sync();
});
```
3. Run and see error in console.

## Link to live example(s)

N/A

# Provide additional details

N/A

## Context

Trying to store metadata in a workbook level range name, in the form of an escaped JSON object.

## Useful logs

- [x] Console errors

Console error:
```
[ERROR]: Error:
{
    "stack": "RichApi.Error: The argument is invalid or missing or has an incorrect format.\n    at new n (https://appsforoffice.microsoft.com/lib/1/hosted/excel-web-16.00.js:25:317442)\n    at i.processRequestExecutorResponseMessage (https://appsforoffice.microsoft.com/lib/1/hosted/excel-web-16.00.js:25:381888)\n    at https://appsforoffice.microsoft.com/lib/1/hosted/excel-web-16.00.js:25:379951",
    "message": "The argument is invalid or missing or has an incorrect format.",
    "name": "RichApi.Error",
    "code": "InvalidArgument",
    "traceMessages": [],
    "innerError": null,
    "debugInfo": {
        "code": "InvalidArgument",
        "message": "The argument is invalid or missing or has an incorrect format.",
        "errorLocation": "NamedItemCollection.add",
        "statement": "var add = names.add(...);",
        "surroundingStatements": [
            "var workbook = context.workbook;",
            "var names = workbook.names;",
            "// >>>>>",
            "var add = names.add(...);",
            "// <<<<<"
        ],
        "fullStatements": [
            "var workbook = context.workbook;",
            "var names = workbook.names;",
            "var add = names.add(\"Test_Range\", \"Hello \\\"Excel\\\" world!\", undefined);"
        ]
    },
    "httpStatusCode": 400
}
```

**Comment by rajatavams** [comment]
Thanks for reporting the issue. We were able to reproduce it and have created an internal work item (#10958234) to track it further. We’ll share updates on its progress here.

**Comment by rajatavams** [comment]
Hello @MitchellNZ , 

The fix has been released. Please let us know if you are still facing the issue.
