### ISSUE TITLE
Use react-router-dom v6

### ISSUE THREAD

**Issue by torrinworx** [OfficeDev/office-js#3799]
Currently using react-router-dom v6 doesn't work, for some reason the routing using the `Routes` component causes issues to arise in ms word add-ins:

<details>
  <summary>Errors (Click me)</summary>
  
```
router.js:345 Uncaught TypeError: globalHistory.replaceState is not a function
    at getUrlBasedHistory (router.js:345:1)
    at createBrowserHistory (router.js:187:1)
    at BrowserRouter (index.js:534:46)
    at renderWithHooks (react-dom.development.js:16305:1)
    at mountIndeterminateComponent (react-dom.development.js:20074:1)
    at beginWork (react-dom.development.js:21587:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:1)
    at invokeGuardedCallback (react-dom.development.js:4277:1)
    at beginWork$1 (react-dom.development.js:27451:1)
getUrlBasedHistory @ router.js:345
createBrowserHistory @ router.js:187
BrowserRouter @ index.js:534
renderWithHooks @ react-dom.development.js:16305
mountIndeterminateComponent @ react-dom.development.js:20074
beginWork @ react-dom.development.js:21587
callCallback @ react-dom.development.js:4164
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
beginWork$1 @ react-dom.development.js:27451
performUnitOfWork @ react-dom.development.js:26560
workLoopSync @ react-dom.development.js:26466
renderRootSync @ react-dom.development.js:26434
performConcurrentWorkOnRoot @ react-dom.development.js:25738
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
queue.<computed> @ task.js:62
run @ task.js:36
eventListener @ task.js:47
router.js:345 Uncaught TypeError: globalHistory.replaceState is not a function
    at getUrlBasedHistory (router.js:345:1)
    at createBrowserHistory (router.js:187:1)
    at BrowserRouter (index.js:534:46)
    at renderWithHooks (react-dom.development.js:16305:1)
    at mountIndeterminateComponent (react-dom.development.js:20074:1)
    at beginWork (react-dom.development.js:21587:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:1)
    at invokeGuardedCallback (react-dom.development.js:4277:1)
    at beginWork$1 (react-dom.development.js:27451:1)
getUrlBasedHistory @ router.js:345
createBrowserHistory @ router.js:187
BrowserRouter @ index.js:534
renderWithHooks @ react-dom.development.js:16305
mountIndeterminateComponent @ react-dom.development.js:20074
beginWork @ react-dom.development.js:21587
callCallback @ react-dom.development.js:4164
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
beginWork$1 @ react-dom.development.js:27451
performUnitOfWork @ react-dom.development.js:26560
workLoopSync @ react-dom.development.js:26466
renderRootSync @ react-dom.development.js:26434
recoverFromConcurrentError @ react-dom.development.js:25850
performConcurrentWorkOnRoot @ react-dom.development.js:25750
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
queue.<computed> @ task.js:62
run @ task.js:36
eventListener @ task.js:47
react-dom.development.js:18687 The above error occurred in the <BrowserRouter> component:

    at BrowserRouter (https://localhost:3000/dist/vendors-node_modules_mui_material_Box_Box_js-node_modules_mui_material_Button_Button_js-node_-a64298.js:45985:5)
    at AppRoutes
    at div
    at https://localhost:3000/dist/vendors-node_modules_mui_material_Box_Box_js-node_modules_mui_material_Button_Button_js-node_-a64298.js:827:66
    at Box (https://localhost:3000/dist/vendors-node_modules_mui_material_Box_Box_js-node_modules_mui_material_Button_Button_js-node_-a64298.js:6892:72)
    at ThemeProvider (https://localhost:3000/dist/vendors-node_modules_mui_material_Box_Box_js-node_modules_mui_material_Button_Button_js-node_-a64298.js:5732:5)
    at ThemeProvider (https://localhost:3000/dist/vendors-node_modules_mui_material_Box_Box_js-node_modules_mui_material_Button_Button_js-node_-a64298.js:6122:5)
    at ThemeProvider (https://localhost:3000/dist/vendors-node_modules_mui_material_Box_Box_js-node_modules_mui_material_Button_Button_js-node_-a64298.js:4741:14)
    at GlobalProvider (https://localhost:3000/dist/taskpane.js:1599:3)
    at App (https://localhost:3000/dist/taskpane.js:718:48)
    at StyledEngineProvider (https://localhost:3000/dist/vendors-node_modules_mui_material_Box_Box_js-node_modules_mui_material_Button_Button_js-node_-a64298.js:5915:5)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
logCapturedError @ react-dom.development.js:18687
update.callback @ react-dom.development.js:18720
callCallback @ react-dom.development.js:13923
commitUpdateQueue @ react-dom.development.js:13944
commitLayoutEffectOnFiber @ react-dom.development.js:23391
commitLayoutMountEffects_complete @ react-dom.development.js:24688
commitLayoutEffects_begin @ react-dom.development.js:24674
commitLayoutEffects @ react-dom.development.js:24612
commitRootImpl @ react-dom.development.js:26823
commitRoot @ react-dom.development.js:26682
finishConcurrentRender @ react-dom.development.js:25892
performConcurrentWorkOnRoot @ react-dom.development.js:25809
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
queue.<computed> @ task.js:62
run @ task.js:36
eventListener @ task.js:47
router.js:345 Uncaught TypeError: globalHistory.replaceState is not a function
    at getUrlBasedHistory (router.js:345:1)
    at createBrowserHistory (router.js:187:1)
    at BrowserRouter (index.js:534:46)
    at renderWithHooks (react-dom.development.js:16305:1)
    at mountIndeterminateComponent (react-dom.development.js:20074:1)
    at beginWork (react-dom.development.js:21587:1)
    at beginWork$1 (react-dom.development.js:27426:1)
    at performUnitOfWork (react-dom.development.js:26560:1)
    at workLoopSync (react-dom.development.js:26466:1)
    at renderRootSync (react-dom.development.js:26434:1)
```
</details>

Currently the only option is to revert to v5 and use the outdated `Switch` component:
https://stackoverflow.com/questions/58071999/how-to-configure-office-js-excel-react-add-in-to-use-react-router-dom-or-alterna

Please consider updating and resolving the issues with react router v6 to allow the usage of the Routes component to make routing simpler and more up to date. Let me know if you would like more information or help reproducing the issues I faced above.

Here is the Routes.jsx file I'm using to produce the issue:
```
import React from "react";
import {
    # HashRouter as Router,
    # Switch,
    Router
    Route,
    Routes,
} from "react-router-dom";

import Home from "../Home";

const AppRoutes = () => {
    return (
        <Router>
            {/* <Switch /> */}
            <Routes>
                <Route path="/" element={<Home />} />
            </Routes>
            {/* </Switch> */}
        </Router>
    );
};

export default AppRoutes;
```

Thank you for reading

**Comment by alexuaua** [comment]
@torrinworx For me, applying the same workaround to preserve `window.replaceHistory` (as mentioned [here](https://stackoverflow.com/questions/58071999/how-to-configure-office-js-excel-react-add-in-to-use-react-router-dom-or-alterna/72682825#72682825)) also works with React Router v6 when using HashRouter.

**Comment by vivekjoshi225** [comment]
@alexuaua - I'm not able to work with RRDv6 & React18.
Tried the override mentioned in your comment as well.

**Comment by alexuaua** [comment]
@vivekjoshi225 what type of router do you use?

**Comment by AndreasDvrs** [comment]
Any ideas why this was closed..? It's getting frustrating since a lot of new versions of libraries depend on > v5 react-router-dom version.. Is there any plan to implement support for v6 or an official workaround..?

**Comment by AndreasDvrs** [comment]
Just in case anyone runs on this again - use MemoryRouter - keeps the history of your navigation in memory - ideal for sandboxed environments like the ones we usually run office.js (my case was an outlook add-in ^^)

**Comment by nikolaz111** [comment]
I'm having the same issue with React Router 7. Using the MemoryRouter solved the issue, but still feels like a workaround instead of a fix. Looks like the office addin javascript is messing with some shared global stuff
