### ISSUE TITLE
Unable to insert content control on footnotes and endnotes body in Word Online

### ISSUE THREAD

**Issue by docu-bill** [OfficeDev/office-js#4373]
# Unable to Get footnotes or endnotes body and insertContent control

eg:
```async function run() {
  await Word.run(async (context) => {
    const body = context.document.getFootnoteBody()
    const cc = body.insertContentControl("RichText")
    await context.sync();
  });
}
```
This works in the desktop but does not work in Word Online.

## Your Environment
* Platform: Windows Office on the web 
* Host: Word
* Office version number: Tracked as of today
* Operating System: Windows
* Browser (if using Office on the web): Chrome
 
## Expected behavior
Expect that Word online works similarly to the desktop

## Current behavior
Error is thrown in online word

```[ERROR]: Error:
{
    "stack": "RichApi.Error: Sorry, something went wrong. Check the OfficeExtension.Error.debugInfo for more information. \n    at new n (https://appsforoffice.microsoft.com/lib/1/hosted/word-web-16.00.js:25:336110)\n    at o.processRequestExecutorResponseMessage (https://appsforoffice.microsoft.com/lib/1/hosted/word-web-16.00.js:25:400557)\n    at https://appsforoffice.microsoft.com/lib/1/hosted/word-web-16.00.js:25:398620",
    "message": "Sorry, something went wrong. Check the OfficeExtension.Error.debugInfo for more information. ",
    "name": "RichApi.Error",
    "code": "GeneralException",
    "traceMessages": [],
    "innerError": null,
    "debugInfo": {
        "code": "GeneralException",
        "message": "Sorry, something went wrong. Check the OfficeExtension.Error.debugInfo for more information. ",
        "errorLocation": "Body.insertContentControl",
        "statement": "var insertContentControl = footnoteBody.insertContentControl(...);",
        "surroundingStatements": [
            "var root = context.root;",
            "var footnoteBody = root.getFootnoteBody();",
            "// Instantiate {footnoteBody}",
            "// >>>>>",
            "var insertContentControl = footnoteBody.insertContentControl(...);",
            "// <<<<<",
            "// Instantiate {insertContentControl}"
        ],
        "fullStatements": [
            "Please enable config.extendedErrorLogging to see full statements."
        ]
    },
    "httpStatusCode": 500
}
```

## Steps to reproduce
Run above code in Word online

## Link to live example(s)

Dont seem to be able to make a gist (since the removal of github I guess)

**Comment by xiruatms** [comment]
Thanks for reporting this. I confirm I can repro this, and we've logged an internal work item [8919541] to address it.

**Comment by jaiswalshubh1** [comment]
Hi @docu-bill ,

Thank you for your patience. As per the internal ticket: 8919541 and after reviewing the reported behavior, we have confirmed that the product is currently functioning as designed. Since this would require a change to the existing product behavior, we are treating it as a feature request rather than a product bug. I am closing this issue. 
If you would like us to consider this enhancement for a future release, please submit your suggestion to the Microsoft Tech Community Ideas Forum or upvote an existing idea. This allows other developers with similar requirements to provide feedback and helps our product teams assess community interest.🔗 Ideas Forum:
[https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365Developer…](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365Developer%E2%80%A6)
Thank you for your understanding and support!

CC: @kustonaut 

Thanks!
Shubham Jaiswal
