### ISSUE TITLE
NAA: Unable to acquire access token in taskpane on Outlook for Windows

### ISSUE THREAD

**Issue by manuelsidler** [OfficeDev/office-js#4846]
## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Version 2409 Build 16.0.18025.20006 64-bit (Beta Channel)
* Operating System: Windows 11
* Browser (if using Office on the web): -
 
## Expected behavior
Acquiring an access token via NAA in a taskpane should work

## Current behavior
Acquiring an access token results in _ServerError_ ("PERSISTENT_ERROR")

azure/msal-browser: 3.22.0

Code snippet:
```typescript
const msalConfig = {
        auth: {
            clientId: 'xxx',
            authority: 'https://login.microsoftonline.com/common'
        },
        system: {
                loggerOptions: {
                    logLevel: LogLevel.Verbose,
                    loggerCallback: (level: LogLevel, message: string) => {
                        switch (level) {
                            case LogLevel.Error:
                                console.error(message)
                                return
                            case LogLevel.Info:
                                console.info(message)
                                return
                            case LogLevel.Verbose:
                                console.debug(message)
                                return
                            case LogLevel.Warning:
                                console.warn(message)
                                return
                        }
                    },
                    piiLoggingEnabled: true
                }
            }
    }

const clientApp = await createNestablePublicClientApplication(msalConfig)

const authRequest = {
    scopes,
    loginHint
}

try {
    const account = clientApp.getAccountByUsername(loginHint)
    const authResult = account
        ? await clientApp.acquireTokenSilent(authRequest)
        : await clientApp.ssoSilent(authRequest)
} catch (error) {
    try {
        const authResult = await clientApp.acquireTokenPopup(authRequest)
    } catch (error) {
    }
}
```

## Steps to reproduce
1. Create an Outlook taskpane add-in
2. Use the snippet above the acquire an access token via NAA

## Link to live example(s)
* GitHub repository with a sample to reproduce the error: https://github.com/manuelsidler/outlook-naa-sample

## Useful logs
```
acquire token silently
App.vue:29 [Thu, 29 Aug 2024 11:38:45 GMT] : [] : @azure/msal-browser@3.22.0 : Info - Emitting event: msal:acquireTokenStart
App.vue:26  [Thu, 29 Aug 2024 11:38:45 GMT] : [] : @azure/msal-browser@3.22.0 : Error - Cached tokens are not found for the account, proceeding with silent token request.
loggerCallback @ App.vue:26
executeCallback @ Logger.ts:152
logMessage @ Logger.ts:136
error @ Logger.ts:160
acquireTokenFromCache @ NestedAppAuthController.ts:396
await in acquireTokenFromCache
acquireTokenSilentInternal @ NestedAppAuthController.ts:287
ssoSilent @ NestedAppAuthController.ts:759
ssoSilent @ PublicClientApplication.ts:334
getGraphAccessToken @ App.vue:58
callWithErrorHandling @ runtime-core.esm-bundler.js:202
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:209
invoker @ runtime-dom.esm-bundler.js:691
App.vue:29 [Thu, 29 Aug 2024 11:38:45 GMT] : [] : @azure/msal-browser@3.22.0 : Info - Emitting event: msal:acquireTokenFailure
App.vue:29 [Thu, 29 Aug 2024 11:38:50 GMT] : [] : @azure/msal-browser@3.22.0 : Info - Emitting event: msal:acquireTokenFailure
App.vue:61  Unable to acquire token silently ServerError
    at NestedAppAuthAdapter.fromBridgeError (NestedAppAuthAdapter.ts:257:28)
    at _NestedAppAuthController.acquireTokenSilentInternal (NestedAppAuthController.ts:344:53)
    at async getGraphAccessToken (App.vue:58:15)
getGraphAccessToken @ App.vue:61
await in getGraphAccessToken
callWithErrorHandling @ runtime-core.esm-bundler.js:202
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:209
invoker @ runtime-dom.esm-bundler.js:691
App.vue:64 acquire token by popup
App.vue:29 [Thu, 29 Aug 2024 11:38:50 GMT] : [] : @azure/msal-browser@3.22.0 : Info - Emitting event: msal:acquireTokenStart
App.vue:29 [Thu, 29 Aug 2024 11:38:50 GMT] : [] : @azure/msal-browser@3.22.0 : Info - Emitting event: msal:acquireTokenFailure
App.vue:68  Unable to acquire token interactively ServerError
    at NestedAppAuthAdapter.fromBridgeError (NestedAppAuthAdapter.ts:257:28)
    at _NestedAppAuthController.acquireTokenInteractive (NestedAppAuthController.ts:252:53)
    at async getGraphAccessToken (App.vue:65:32)
```

**Comment by davidchesnut** [comment]
Hi @manuelsidler,,

Thanks for letting us know about this issue. I tested the task pane code on beta channel and it works. However a newer build is out since you tried this. Can you try again with the new build (which is 18028.20004)?

If it still doesn't work I would check your app registration. It needs to have the brk-multihub redirect. Were there any other changes beyond that?

Also I tried the link to your GitHub repo, but it's a broken link. Happy to try your code directly if you have a link.

Thanks!
David

**Comment by manuelsidler** [comment]
Hi @davidchesnut 

It works with the new build (18028.20004). I also double checked with Outlook on the web and Outlook Mac (16.88.1 24082514). Acquiring an access token via NAA inside the taskpane works as expected.

Thanks!

**Comment by zhngx1** [comment]
Closing the issue. @manuelsidler Please let us know if you run into new issues.
