### ISSUE TITLE
Error creating Custom Ribbon Tab controls by RibbonAPI on Excel Online

### ISSUE THREAD

**Issue by valse** [OfficeDev/office-js#4869]
Hi, we're devloping a new Excel add-in with a Task Pane and a Custom Ribbon Tab created and updated through the APIs

## Expected Behavior
Using the `Office.ribbon.requestCreateControls` api call the new tab is shown in the menu

## Current Behavior
The Tab is created on the Excel for Desktop but not in the Excel for Web

## Steps to Reproduce, or Live Example
``` js
$("#run").on("click", () => tryCatch(run));

async function run() {
  await Excel.run(async (context) => {
    Office.ribbon.requestCreateControls({
      actions: [{
        id: "my_action_connect",
        type: "ExecuteFunction",
        functionName: "connect"
      }],
      tabs: [{
        id: 'my_addin_ribbon',
        label: 'Test',
        visible: true,
        groups: [
          {
            id: "my_addin_ribbon_connection",
            label: 'Connection',
            controls: [
              {
                type: 'Button',
                id: 'brd_addin_ribbon_connection_connect',
                actionId: "my_action_connect",
                enabled: false,
                label: 'Connect',
                superTip: {
                  title: 'Connect',
                  description: 'Use this button to connect.'
                },
                icon: [
                  {
                    size: 32,
                    sourceLocation: `/connect-ok-32-blue.png`
                  },
                  {
                    size: 80,
                    sourceLocation: `/connect-ok-32-blue.png`
                  }
                ]
              }
            ]
          }
        ]
      }]
    })
  });
}

/** Default helper for invoking an action and handling errors. */
async function tryCatch(callback) {
  try {
    await callback();
  } catch (error) {
    // Note: In a production add-in, you'd want to notify the user through your add-in's UI.
    console.error(error);
  }
}
```

## Context
We'd like to manage the Tab by the apis and not created static on the manifest file

## Your Environment
* Platform [PC desktop, Mac, iOS, Office Online]: PC desktop, Office Online
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Operating System: Windows 11
* Browser (if using Office Online): Edge

## Useful logs
On my application I have this error on console but using the ScriptLab no errors are catched:
``` js
RichApi.Error: The requested resource doesn't exist.
```

Thanks 😉

**Comment by gmichaud** [comment]
@valse does it sometimes work? For us the ribbon API works reliably on Excel for Windows and Mac, but for Excel Online it's hit or miss -- sometimes after reloading the page 3-4 times it eventually shows up. It's been like that for as long as I remember.

**Comment by shanshanzheng-dev** [comment]
Hi @valse Thanks for reporting this issue. I run this code using the ScriptLab no errors are catched, either. Could you share us your manifest? 
@m-hellesen could you please take a look? Thanks.

**Comment by valse** [comment]
> Hi @valse Thanks for reporting this issue. I run this code using the ScriptLab no errors are catched, either. Could you share us your manifest? @m-hellesen could you please take a look? Thanks.

Hi @shanshanzheng-dev... yes with ScriptLab non errors are catched but did you see the new "Test" tab on the Excel Online? Running the script I can see it on the Excel Desktop only. Thanks

**Comment by shanshanzheng-dev** [comment]
> > Hi @valse Thanks for reporting this issue. I run this code using the ScriptLab no errors are catched, either. Could you share us your manifest? @m-hellesen could you please take a look? Thanks.
> 
> Hi @shanshanzheng-dev... yes with ScriptLab non errors are catched but did you see the new "Test" tab on the Excel Online? Running the script I can see it on the Excel Desktop only. Thanks

Yes, I can see a new "Test" tab on Excel Desktop only. We'll take a look, but unfortunately we can't share a timeline.

**Comment by mayurandhare13** [comment]
Hi @valse, 
The example you shared using script lab might not work. As, adding custom contextual tabs requires your add-in to use the shared runtime.

https://learn.microsoft.com/en-us/office/dev/add-ins/design/contextual-tabs

I think you already have excel add-in. Could you please make it Shared Runtime one.
Also, custom contexual tab is not visible by default even if we specify the visibility property. I understand this might be working on desktop. But for excel-online (_and as per document_) it's not visible. Could you please set it with `requestUpdate`. In the above link, there are multiple examples.
```
    await Office.ribbon.requestUpdate({
        tabs: [
            {
                id: "CtxTab1",
                visible: true
            }
        ]});
```

Please let me know if this works.

**Comment by valse** [comment]
Hi @mayurandhare13,

Thanks for your help. Our add-in is already working in a Shared Runtime context.

I am updating the tab using the `requestUpdate` method, but I am encountering the following error:

```
RichApi.Error: Cannot find the specified control ID:my_addin_ribbon
    at new n (excel-web-16.00.js:25:322528)
    at i.processRequestExecutorResponseMessage (excel-web-16.00.js:25:387690)
    at excel-web-16.00.js:25:385751
    at _ZoneDelegate.invoke (zone.js:365:28)
    at Object.onInvoke (core.mjs:14882:33)
    at _ZoneDelegate.invoke (zone.js:364:34)
    at ZoneImpl.run (zone.js:111:43)
    at zone.js:2498:40
    at _ZoneDelegate.invokeTask (zone.js:398:33)
    at core.mjs:14556:55 {action: 'brd_action_create_table', enabled: true}
```

I created the tab using the `Office.ribbon.requestCreateControls` method, and it works on Windows Excel Desktop. However, it seems that this command does not create the tab in the web version.

If I create the tab in the manifest, I can see it in the web version. However, if I try to update it using the `requestUpdate` command, I no longer get an error, but nothing happens. The Desktop client also exhibits the same behavior with the pre-configured custom tab.

**Comment by mayurandhare13** [comment]
@valse Its working for me. Do you see any errors in the console when creating custom contextual tab when you are using `requestCreateControls` in your shared runtime addin (_not with script lab_)? Could you please provide more details as I am not able to repro this issue.

**Comment by mayurandhare13** [comment]
@valse I went through attached bug. Have you tried their suggestion `await delay(seconds(0.5))` / or maybe try wait for longer time? This will narrow down the issue.

Have you deployed your addin? I could try out that.

This is my simple ribbon updater data looks like. I first launch the addin taskpane, then I have button which invokes "requestCreateControl". Although by default it doesn't show the custom context tab "CtxTabA1" but invoking requestUpdate shows it.

```
var defaultribbondef = {
    actions: [
        {
            id: "executeHideTabs",
            type: "ExecuteFunction",
            functionName: "hideContextualTabs",
        },
        {
            id: "executeShowTabs",
            type: "ExecuteFunction",
            functionName: "showContextualTabs",
        }
    ],
    tabs: [
        {
            id: "CtxTabA1",
            label: "CtxTabA1",
            visible: true,
            groups: [
                {
                    id: "CustomGroup111",
                    label: "Group11Title",
                    icon: [
                        {
                            size: 16,
                            sourceLocation:
                                "https://localhost/images/TaskPanes.32x32x32.png",
                        },
                        {
                            size: 32,
                            sourceLocation:
                                "https://localhost/images/TaskPanes.32x32x32.png",
                        },
                        {
                            size: 80,
                            sourceLocation:
                                "https://localhost/images/TaskPanes.32x32x32.png",
                        },
                    ],
                    controls: [
                        {
                            type: "Button",
                            id: "CtxBt112",
                            enabled: false,
                            icon: [
                                {
                                    size: 16,
                                    sourceLocation:
                                        "https:/localhost/images/TaskPanes.32x32x32.png",
                                },
                                {
                                    size: 32,
                                    sourceLocation:
                                        "https://localhost/images/TaskPanes.32x32x32.png",
                                },
                                {
                                    size: 80,
                                    sourceLocation:
                                        "https://localhost/images/TaskPanes.32x32x32.png",
                                },
                            ],
                            label: "ExeFuncHideTabs_CtxBt112",
                            actionId: "executeHideTabs",
                        },
                    ],
                },
            ],
        },
    ],
};
```

**Comment by mayurandhare13** [comment]
I see in case of Velixo, `requestUpdate` call is made explicitly. So, I also tried same and wait for 1 seconds, it works for me. Could you please try this.

```
    Office.ribbon.requestCreateControls(JSON.parse(ribbonTabDefinition))
        .then(function () {
            setTimeout(function () {
                callRequestUpdate(true);
            }, 1000);
         })
```

**Comment by wh1t3cAt1k** [comment]
It's better with a delay but still hit-or-miss for us. https://github.com/OfficeDev/office-js/issues/5397 – it would be great if it could be fixed once and for all without needing kludges...

**Comment by valse** [comment]
Hi,
I've finally resolved the issue!

Based on the ribbon schema:
https://developer.microsoft.com/json-schemas/office-js/dynamic-ribbon.schema.json

I noticed that we were missing the icon property in the group element.
Even though the icon isn't displayed, it's still a required property because the group element extends the iconElement.

Interestingly, this requirement only applies to the web version—on the desktop version, it works fine without it.
According to the schema, the icon array should contain at least one element, but providing an empty icon array in the group element also works.
It seems the web app uses a stricter schema validator.
