### ISSUE TITLE
Office.context.ui.displayDialogAsync not working in "the new Outlook"

### ISSUE THREAD

**Issue by pajama61** [OfficeDev/office-js#496]
## Expected Behavior
Dialolg opens and callback called on completion.

## Current Behavior
Only repros when "The new Outlook" is toggled on.
The dialog doesn't show up and the callback is never called.
When exiting, a warning is shown that "Add-in still working".

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: Office Online
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Office365
* Operating System: Linux
* Browser (if using Office Online): Chrome

## Useful logs
Console logged an uncaught exception:
outlook-web-16.01.js:16 Uncaught Sys.ArgumentNullException: Sys.ArgumentNullException: Value cannot be null.
Parameter name: conversationId
    at Function.Error.create (https://ajax.aspnetcdn.com/ajax/3.5/MicrosoftAjax.js:5:2732)
    at Function.Error.argumentNull (https://ajax.aspnetcdn.com/ajax/3.5/MicrosoftAjax.js:5:3196)
    at Function._validateParameterType (https://ajax.aspnetcdn.com/ajax/3.5/MicrosoftAjax.js:5:1648)
    at Function._validateParameter (https://ajax.aspnetcdn.com/ajax/3.5/MicrosoftAjax.js:5:1080)
    at Function._validateParams (https://ajax.aspnetcdn.com/ajax/3.5/MicrosoftAjax.js:5:629)
    at new Microsoft.Office.Common.ClientEndPoint (https://appsforoffice.microsoft.com/lib/1/hosted/outlook-web-16.01.js:16:87609)
    at Object.connect (https://appsforoffice.microsoft.com/lib/1/hosted/outlook-web-16.01.js:16:95709)
    at OSF.InitializationHelper.setAgaveHostCommunication (https://appsforoffice.microsoft.com/lib/1/hosted/outlook-web-16.01.js:16:113376)
    at o (https://appsforoffice.microsoft.com/lib/1/hosted/office.js:18:24766)
    at d (https://appsforoffice.microsoft.com/lib/1/hosted/office.js:18:3609)

However this is also thrown when *not* using the new Outlook, and the dialog worked as expected.

**Comment by tobiasviehweger** [comment]
Possibly same as #467?

**Comment by pajama61** [comment]
Yes, exactly the same as #467
