### ISSUE TITLE
Error when adding rows to table using Excel JS library with a specific sheet

### ISSUE THREAD

**Issue by buzzo123** [OfficeDev/office-js#4991]
**Description**:  
I am encountering an issue when attempting to add rows to a table using the Excel JS library while a specific sheet is opened. The issue persists only with this particular sheet, which is attached.

**Environment**:
- Excel version: _Microsoft® Excel® for Microsoft 365 MSO (Version 2409 Build 16.0.18025.20030) 64-bit_ 
- Office.js version:  _"@microsoft/office-js": "^1.1.94"_
- Platform: _Windows 11_

The following code triggers the error:

```javascript
async function createTable() {
  await Excel.run(async (context) => {
    context.workbook.worksheets.getItemOrNullObject("Sample").delete();
    const sheet = context.workbook.worksheets.add("Sample");

    const expensesTable = sheet.tables.add("A1:D1", true /*hasHeaders*/);
    expensesTable.name = "ExpensesTable";

    expensesTable.getHeaderRowRange().values = [["Date", "Merchant", "Category", "Amount"]];

    expensesTable.rows.add(null /*add at the end*/, [
      ["1/1/2017", "The Phone Company", "Communications", "$120"],
      ["1/2/2017", "Northwind Electric Cars", "Transportation", "$142"],
      ["1/5/2017", "Best For You Organics Company", "Groceries", "$27"],
      ["1/10/2017", "Coho Vineyard", "Restaurant", "$33"],
      ["1/11/2017", "Bellows College", "Education", "$350"],
      ["1/15/2017", "Trey Research", "Other", "$135"],
      ["1/15/2017", "Best For You Organics Company", "Groceries", "$97"]
    ]);

    sheet.getUsedRange().format.autofitColumns();
    sheet.getUsedRange().format.autofitRows();

    sheet.activate();

    await context.sync();
  });
}
```

**Steps to Reproduce**:  
1. Open the attached sheet in Excel.
2. Run the above script to add rows to the table.
3. Observe the error in the console.

**Console Error Message**:  
```  
[ERROR]: Error:
{
    "stack": "RichApi.Error: There was an internal error while processing the request.\n    at new n (https://appsforoffice.microsoft.com/lib/1/hosted/excel-win32-16.01.js:25:265694)\n    at r.processRequestExecutorResponseMessage (https://appsforoffice.microsoft.com/lib/1/hosted/excel-win32-16.01.js:25:330663)\n    at https://appsforoffice.microsoft.com/lib/1/hosted/excel-win32-16.01.js:25:328724",
    "message": "There was an internal error while processing the request.",
    "name": "RichApi.Error",
    "code": "GeneralException",
    "traceMessages": [],
    "innerError": null,
    "debugInfo": {
        "code": "GeneralException",
        "message": "There was an internal error while processing the request.",
        "errorLocation": "TableRowCollection.add",
        "statement": "var add2 = rows.add(...);",
        "surroundingStatements": [
            "...",
            "add1.name = ...;",
            "var headerRowRange = add1.getHeaderRowRange();",
            "// Instantiate {headerRowRange}",
            "headerRowRange.values = ...;",
            "var rows = add1.rows;",
            "// >>>>>",
            "var add2 = rows.add(...);",
            "// <<<<<",
            "var usedRange = add.getUsedRange();",
            "// Instantiate {usedRange}",
            "var format = usedRange.format;",
            "format.autofitColumns();",
            "var usedRange1 = add.getUsedRange();",
            "..."
        ],
        "fullStatements": [
            "Please enable config.extendedErrorLogging to see full statements."
        ]
    },
    "httpStatusCode": 500
}
```

**Expected Result**:  
The rows should be added successfully to the table on the specified sheet.

**Actual Result**:  
The script fails with a `GeneralException` (HTTP 500 error) at `TableRowCollection.add`.

**Questions**:
- Can you help me identify why this error appears?
- Why would an error in a sheet be related to a new table creation in another sheet?

**Additional Information**:  
I have attached the problematic sheet file for reference.

[error_sheet.xlsx](https://github.com/user-attachments/files/17461682/error_sheet.xlsx)

**Comment by buzzo123** [comment]
I just wanted to highlight that this is an urgent matter because our users are experiencing malfunctions, and they are unable to identify the specific sheets causing the problem. This is impacting their workflows significantly. A timely resolution would be greatly appreciated as it directly affects their ability to work efficiently.
Thanks again for your support!

**Comment by qinliuMSFT** [comment]
Thank you for reporting this issue, I can repro it. It has been put on our backlog # 9468822, the team will investigate and we will reply to you as soon as there is any progress. Thank you for your patience.

Meanwhile, could you please share the name of the add-in? Or you can provide the scale of affected users, it will help us re-prioritize this bug.

**Comment by buzzo123** [comment]
The add-in is a custom software solution that helps users create forms and retrieve data from a database. It is currently not available in the public store but is distributed through the Microsoft 365 Admin Center for our customers' organizations. After retrieving data with the add-in, users often customize the sheet, and I suspect this customization is responsible for the bug, causing all subsequent table creation via Excel.js to fail. However, I am unable to pinpoint exactly why this happens.

This issue is affecting multiple users across different organizations, making it difficult for them to complete their tasks effectively. We would appreciate any assistance in prioritizing this bug, as it’s having a significant impact on user productivity.

**Comment by XuanZhouMSFT** [comment]
Hi @buzzo123 Thanks for reporting this issue and waiting. I did a quick investigation and found the issue with the specific file should be related to conditional format you set for the table in "error" worksheet.

I see there're a bunch of duplicated conditional formats set to the table like below. It only show a part of the conditional formats.
<img width="712" alt="image" src="https://github.com/user-attachments/assets/4c15fdbb-0fd4-42db-bdfb-457e806d5beb">

And if you clear the conditional formats or just remove the duplication conditional formats, the issue is gone.
<img width="714" alt="image" src="https://github.com/user-attachments/assets/2ab257f0-b348-454b-9edd-c50a7688cb91">

**Comment by buzzo123** [comment]
Thanks @XuanZhouMSFT for the guidance! 
However, could you explain why a broken sheet with duplicated conditional formatting impacts the entire workbook’s functionality? I’d like the add-in to remain functional at least on the 'good' sheets. Ideally, I’d be able to identify the problematic sheet, inform users, and allow continued interaction with unaffected sheets.

**Comment by XuanZhouMSFT** [comment]
Hi @buzzo123. 
I see you're using the API table.add. Inside this API, it will insert rows for the table which will cause a lot of adjust action for dependency, like conditional formatting, comments, etc...
It's not exactly related to the "duplicate" thing because if I just duplicate a conditional format, it will also work. The problem is related some broken conditional formatting there, but it's hard for me to identify which one is the root cause as there're so many conditional formatting there. If you have any insights about how the bunch of duplicate conditional formatting happens, it should also help.

**Comment by buzzo123** [comment]
@XuanZhouMSFT The challenge is that this issue isn’t isolated to the problematic sheet—it’s impacting interactions across the entire Excel file, even in sheets without any broken or duplicated conditional formatting. Could there be a way for the API to isolate the problem, so interactions on unaffected (or 'good') sheets can continue working independently?

I understand that fixing or deleting the problematic sheet is likely necessary. However, this issue currently affects the entire workbook, including 'good' sheets, which disrupts overall functionality. It would be helpful to have a solution that at least lets users continue working on unaffected sheets while the broken sheet is addressed

**Comment by XuanZhouMSFT** [comment]
@buzzo123  Totally understand your pain points. But the adjust for the dependent action is needed and can't be avoid because of the insert action. For example, if you only add the table in the workbook. And directly do the insert row action from UI, the error will still happen.

To workaround your concern, if your customers will always have some problem workbook. Suggest you to avoid the insert row/column actions. And you can use set values for the table instead.

**Comment by buzzo123** [comment]
@XuanZhouMSFT 
My basic reasoning is the following: **The broken sheet shouldn't affect the functionality of the sheets that are operational**.

While I understand the need for adjustments due to dependencies, it would be beneficial to have a solution that allows users to work on unaffected sheets, even if a problematic sheet exists.
Do you agree with me?

**Comment by buzzo123** [comment]
It seems there may have been a misunderstanding. I’m referring to adding rows to a table that belongs **to a different sheet**, not the one that is broken. My goal is to ensure that operations on the unaffected sheets remain functional, regardless of the issues on the problematic sheet.
