### ISSUE TITLE
Error when renaming a sheet and adding rows via Excel.js

### ISSUE THREAD

**Issue by buzzo123** [OfficeDev/office-js#4998]
**Description**:  
I am encountering an error when trying to rename a sheet in Excel while also adding rows to a table using the Excel JS library. The error occurs when renaming the sheet is initiated but not completed, and rows are added programmatically. 

**Environment**:
- Excel version: Microsoft® Excel® for Microsoft 365 MSO (Version 2409 Build 16.0.18025.20030) 64-bit
- Office.js version: "@microsoft/office-js": "^1.1.94"
- Platform: Windows 11

**Steps to Reproduce**:
1. Attempt to rename a sheet.
2. While the sheet is in renaming mode, run the following script:

```javascript
async function createTable() {
  await Excel.run(async (context) => {
    context.workbook.worksheets.getItemOrNullObject("Sample").delete();
    const sheet = context.workbook.worksheets.add("Sample");

    const expensesTable = sheet.tables.add("A1:D1", true /*hasHeaders*/);
    expensesTable.name = "ExpensesTable";

    expensesTable.getHeaderRowRange().values = [["Date", "Merchant", "Category", "Amount"]];

    const rows = [["1/1/2017", "The Phone Company", "Communications", "$120"]];
    expensesTable.rows.add(undefined, rows);
    sheet.activate();
    await context.sync();
  });
}
```

3. Observe the following error in the console:

**Error Log**:
```json
[ERROR]: Error:
{
    "stack": "RichApi.Error: There was an internal error while processing the request.\n    at new n (https://appsforoffice.microsoft.com/lib/1/hosted/excel-win32-16.01.js:25:265694)\n    at n.processRequestExecutorResponseMessage (https://appsforoffice.microsoft.com/lib/1/hosted/excel-win32-16.01.js:25:330663)\n    at https://appsforoffice.microsoft.com/lib/1/hosted/excel-win32-16.01.js:25:328724",
    "message": "There was an internal error while processing the request.",
    "name": "RichApi.Error",
    "code": "GeneralException",
    "traceMessages": [],
    "innerError": null,
    "debugInfo": {
        "code": "GeneralException",
        "message": "There was an internal error while processing the request.",
        "errorLocation": "Worksheet.delete",
        "statement": "itemOrNullObject.delete();",
        "surroundingStatements": [
            "var workbook = context.workbook;",
            "var worksheets = workbook.worksheets;",
            "var itemOrNullObject = worksheets.getItemOrNullObject(...);",
            "// >>>>>",
            "itemOrNullObject.delete();",
            "// <<<<<",
            "var add = worksheets.add(...);",
            "var tables = add.tables;",
            "var add1 = tables.add(...);",
            "add1.name = ...;",
            "var headerRowRange = add1.getHeaderRowRange();",
            "..."
        ],
        "fullStatements": [
            "Please enable config.extendedErrorLogging to see full statements."
        ]
    },
    "httpStatusCode": 500
}
```

**Expected Result**:  
The table rows should be added without any errors.

**Actual Result**:  
An internal error occurs, causing the process to fail when attempting to delete and recreate the worksheet, breaking the row addition logic.

**Additional Information**:  
This error is not expected in our workflow and disrupts the code execution. Any assistance in identifying the root cause and resolving this issue would be greatly appreciated.

**Comment by qinliuMSFT** [comment]
Thank you for reporting this issue, I can repro it. It has been put on our backlog #9472329 , the team will investigate and we will reply to you as soon as there is any progress. Thank you for your patience.

**Comment by chandpravandan** [comment]
@buzzo123 we have updated the error message in this case, can you please try to repro this on the latest version of Excel on Desktop

**Comment by chandpravandan** [comment]
@buzzo123 closing this issue, since there are no pending actions on our side

please feel free to create a new github issue, if it repro's
