### ISSUE TITLE
Outlook Crash in Legacy Mac UI with Mixed Attachments

### ISSUE THREAD

**Issue by sagarkhatriseclore** [OfficeDev/office-js#5034]
## Expected Behavior
Mail should get send without any issue.

## Current Behavior
I’m encountering an issue in the legacy UI on Mac where Outlook crashes under one specific condition: when both an inline attachment and a regular attachment are added to the email. All other cases work without issue in the legacy UI on Mac.

* Additional details:
I have an Outlook add-in deployed that performs processing before sending emails. It’s working smoothly across various environments, including:

- All major browsers, including Safari
- Windows Outlook (new UI)
- New Outlook UI on Mac

However, I’m encountering an issue in the legacy UI on Mac where Outlook crashes under one specific condition: when both an inline attachment and a regular attachment are added to the email. All other cases work without issue in the legacy UI on Mac.

We are specifically seeing this issue on outlook 16.90, everything is working fine on 16.88.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office Online]: Mac outlook legacy ui

## Useful logs
Dump of the crash:
```
Microsoft Error Reporting log version: 2.0
Error Signature:
Exception: EXC_BAD_ACCESS
ExceptionEnumString: 1
Exception Code: KERN_INVALID_ADDRESS (0x00001903694d71a0)
Date/Time: 2024-10-31 12:59:24 +0000
Application Name: Microsoft Outlook
Application Bundle ID: com.microsoft.Outlook
Application Signature: OPIM
Application Bitness: x64
Application Version: 16.90.2.24102719
Crashed Module Name: Microsoft Outlook
Crashed Module Version: 16.90.24102719
Blame Module Name: Microsoft Outlook
Stack Trace:
#1 0x0000000105e65584 in (Microsoft Outlook + 0x0000000001295584)
#2 0x000000018ba57180 in ___CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ (CoreFoundation + 0x0000000000073180)
#...

```

**Comment by mmanjaree-msft** [comment]
@sagarkhatriseclore Are attachments added by addin? Is the issue still there when you try to add attachments manually without any addin?

**Comment by sagarkhatriseclore** [comment]
Yes, the regular attachment is added by the add-in, while the inline attachment is manually added in the compose pane. In this scenario, we encounter the issue on the legacy Outlook for Mac (version 16.90).

There are no issues if attachments are added manually.

Additionally, if only regular attachments are added by the add-in (with no inline attachments), we don’t experience any problems.

The failure scenario—where an inline attachment is manually added alongside regular attachments added by the add-in—works fine on Windows and in all browsers.

**Comment by sagarkhatriseclore** [comment]
Hi team, @mmanjaree-msft , good day! 
I wanted to follow up to see if there’s any update on this. This issue is impacting us and our customer, so any help would be greatly appreciated

**Comment by mmanjaree-msft** [comment]
Thanks for the info provided. We are trying to get a repro for the issue mentioned above. Will keep this post updated. Just to clarify, problematic scenario is only when an inline addin is present and addin adds an attachment (in any order)

**Comment by sagarkhatriseclore** [comment]
Thank you @mmanjaree-msft for your quick reply.

Yes, the problematic scenario occurs only when an inline attachment is present, and the add-in adds an attachment (in any order). One key observation we've made is that it fails mostly if the add-in also calls the saveMail Office.js API.

This issue appears similar to one resolved in versions 16.89 (24081812) and 16.89 (24082024) of Outlook for Mac, which addressed crashes occurring when saving a draft email that included both inline and regular attachments. Here’s the release note:

"Crash: Fixed an issue that was causing Outlook to crash when saving an email message in draft that has an inline and/or a normal attachment."

You can review the release notes here:
https://support.microsoft.com/en-us/office/outlook-for-mac-release-notes-for-beta-channel-builds-d6347358-5613-433e-a49e-a9a0e8e0462a

Key Difference:
In our scenario, the regular attachments are added by the add-in, and saveMail is triggered by the add-in rather than manually saving the email as a draft.

**Comment by sagarkhatriseclore** [comment]
Thank you @mmanjaree-msft  for your quick reply.

Yes, the problematic scenario occurs only when an inline attachment is present, and the add-in adds an attachment (in any order). One key observation we've made is that it fails only if the add-in also calls the saveMail Office.js API.

**Comment by anjalitp** [comment]
@sagarkhatriseclore   We are not able to reproduce the crash on our side. Could you please provide exact repro steps before the crash occurs including the part where Add-in calls saveAsync API? You could also share the repro video if possible.
Also, please share the entire crash log with us.

**Comment by sagarkhatriseclore** [comment]
Hi @anjalitp ,

I am reaching out to provide the detailed steps to reproduce an issue we've encountered with the Outlook add-in. Below are the steps that lead to a crash in the Outlook client.

Steps to Reproduce:

1. Click on New Mail.
2. Add 1 inline attachment.
3. Add a regular attachment.
4. Launch the Add-in:
The add-in will fetch the attachments, remove them from the compose pane for processing, perform specific tasks on each attachment, and call saveAsync every 5 seconds if a certain condition is met during attachment fetching and processing.

5. Click Send:
On sending, the add-in will re-add the attachments back to the compose pane.
After the attachments are re-added and the add-in has completed its work, when Outlook attempts to send the email, it crashes.


**[Outlook Error Dump.txt](https://github.com/user-attachments/files/17662164/Outlook.Error.Dump.txt)**

If only a regular attachment is added (without an inline attachment), the same processing steps occur in the add-in, but Outlook functions as expected without crashing.
I've attached a screen recording of the issue and the crash dump for your review.

Please let us know if further details are needed to address this issue.

https://github.com/user-attachments/assets/9f7b790b-34a5-4cec-9eae-70fa3bddaf0c

**Comment by PratikSavla** [comment]
Hi, even I am facing similar issue. Following are the details:

Issue: Outlook client crashes when sending a mail with inline attachment while task pane add-in has Office.EventType.AttachmentsChanged event handler attached to it.

Repro steps (Step by Step):
1. Deploy an xml outlook officejs add-in which has an event handler for attachments changed in taskpane.
2. Draft a mail with at least 1 inline attachment.
3. Invoke taskpane add-in. Make sure Attachments Changed event handler is running in background.
4. Click on the send button.

Expected Behavior: Mails should be sent successfully. Outlook client should not crash.
Actual Behavior: Outlook crashes when the send button is clicked.

Sample code (script lab yaml): 
```
name: Blank snippet
description: Create a new snippet from a blank template.
host: OUTLOOK
api_set: {}
script:
  content: |
    $("#run").on("click", run);
 
    function run() {
      Office.context.mailbox.item.addHandlerAsync(Office.EventType.AttachmentsChanged, (val) => { console.log("recieved event::", JSON.stringify(val)); }, () => { console.log("added handler successfully");});
    }
  language: typescript
template:
  content: |
    <button id="run" class="ms-Button"><span class="ms-Button-label">Run</span></button>
  language: html
style:
  content: |-
    section.samples {
        margin-top: 20px;
    }
 
    section.samples .ms-Button, section.setup .ms-Button {
        display: block;
        margin-bottom: 5px;
        margin-left: 20px;
        min-width: 80px;
    }
  language: css
libraries: |
  https://appsforoffice.microsoft.com/lib/1.1/hosted/office.js
  @types/office-js
  office-ui-fabric-core@11.1.0/dist/css/fabric.min.css
  office-ui-fabric-js@1.5.0/dist/css/fabric.components.min.css
  core-js@2.4.1/client/core.min.js
  @types/core-js
  jquery@3.1.1
  @types/jquery@3.3.1
```

**Comment by anjalitp** [comment]
Thanks for providing more details. We have an in-house repro of this issue. This has been added to our backlog. Unfortunately, we do not have a timeline to share at this point.

**Comment by PratikSavla** [comment]
Hi,

This issue is observed in our development setup and also from the customers who have this plugin deployed.
We have many customers ( in hundreds) and all have not moved to New Outlook where outlook is not crashing due to ```Office.context.mailbox.item.addHandlerAsync(Office.EventType.AttachmentsChanged...```

What do you recommend we should be doing instead of AttachmentsChanged event handler for monitoring outlook attachments? Should we call [Office.context.mailbox.item.getAttachmentsAsync](https://learn.microsoft.com/en-us/javascript/api/outlook/office.messagecompose?view=outlook-js-preview#outlook-office-messagecompose-getattachmentsasync-member(1)) method every second?
