### ISSUE TITLE
Request for isSetSupported sometimes fails with undefined in Outlook Desktop

### ISSUE THREAD

**Issue by bogdanst24** [OfficeDev/office-js#5091]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC Desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Any
* Operating System: Windows
* Browser (if using Office on the web): -
 
## Expected behavior

Office.context.requirements.isSetSupported('Mailbox'), version: string) is part of Mailbox 1.0 and should work every time on all environments.

## Current behavior

In the past 7 days only, we had 12.000 exceptions from at least 33 customers, and 140 users about being unable to get property 'isSetSupported'. As there are different users from different customers, there are very low chances this would be caused by a specific Office version. The code is as simple as 
```
function getIsMailboxSetSupported(version: string) {
  return Office.context.requirements.isSetSupported('MailBox', version);
}
```
In all cases the platform is Outlook Desktop, Windows. Few observations:
- The issue is not new. It has been happening for a few months already and the exception rate is constant (over 10k a week). The number might be bigger because of some previous exception tracing limitations we had, now solved with the new URLS from the new requirement set. It will though take some time for everyone to update to a supported version.
- It is an error that we are only able to see in our exception logs. We never received log files from customers reporting issues containing this. **However**, we have plenty of users reporting that automatic events are not working and they have to restart Outlook
- The only possible explanation I have, would be that OfficeJs does not initialize in time in Outlook Dekstop, and at the time the event is triggered the `requirements` is not yet accessible. Though, then why would the event be triggered? Went again through the entire documentation and all samples and I cannot see anything wrong in what we are doing. The application is written in typescript and then transpiled to ES6.

```
void Office.onReady(() => {});

Office.actions.associate(
  'onMessageComposeHandler',
  (event: Office.AddinCommands.Event) =>
    void onMessageComposeHandler(......),
);

function onMessageComposeHandler(....) {
 ....
   getIsMailboxSetSupported(...);
 ...
}
```

## Steps to reproduce

I could not reproduce it locally.

## Useful logs

Exception
`
"message":"Unable to get property 'isSetSupported' of undefined or null reference","description":"Unable to get property 'isSetSupported' of undefined or null reference","number":-2146823281,"stack":"TypeError: Unable to get property 'isSetSupported' of undefined or null reference\n at jt (Unknown script code:1:48283)\n at Yt (Unknown script code:5:431)\n at Anonymous function (Unknown script code:6:15945)\n at Generator.prototype.next (native code)\n at Anonymous function (Unknown script code:6:15251)\n at B (Unknown script code:9:38596)\n at Gr (Unknown script code:6:15079)\n at $r (Unknown script code:6:15909)\n at fe (Unknown script code:6:15335)\n at Anonymous function (Unknown script code:6:17319)"
`

**Comment by anjalitp** [comment]
@bogdanst24  Are you referring to Classic Outlook or New Outlook on Windows?

**Comment by bogdanst24** [comment]
Classic Outlook only

**Comment by Oleg-O** [comment]
Thanks, we'll look into this.

**Comment by timwan10** [comment]
Want to confirm you are doing this for LaunchEvents, and this problem isn't happening inside a taskpane?

Is it possible to get more of the code there? there are some "...." left out. Is it possible you are calling isSetSupported somehow before initialize has finished? (your sample code doesn't seem to be doing this though). 

Could just doing: 
`Office.actions.associate( 'onMessageComposeHandler', onMessageComposeHandler); `

Is there something else you are doing in the arrow function that is left out of the copy/pasted code?

**Comment by timwan10** [comment]
Talking to the dev team, it would be very unexpected if the event handler function is called before initialize/OnReady has finished. 

Is it possible that the code onMessageComposeHandler or getIsMailboxSetSupported is being called outside an event handler somewhere?

**Comment by bogdanst24** [comment]
Lunch events and everything happens either inside onNewMessageCompose or onMessageRecipientsChanged. Nothing outside of these. We also have taskpane, but the exceptions are reported from the event based part.

This problem is only seen for some users, not all.

**Comment by timwan10** [comment]
When this happens is the Office.context.mailbox.item object also unavailable? (.item and .requirements get initialized around the same time, so that's why I'm asking...and failures in the item object would be much more severe) 

right now the dev team doesn't have any widespread reports of this aside from yours. (but it could also be that issetsupported isn't a widely used function among developers). But we haven't seen any reports of mailbox.item failing 

it's hard to take actionable steps here without a repro. 

Is there anyway you can post more of your code involving everywhere that references onNewMessageCompose and onMessageRecipientsChanged? Or maybe the full callstack of the exception unminified?

Your analysis is correct that the code is being called before initialization is completed (that's where stuff like item and requirements are defined). 

But you shouldn't be called on your events before that happens. Which probably means either: 

1) There is a bug, and Outlook client IS calling your event before init 
2) There is a bug during some of the initialization process and the requirements object isn't created. 
3) Somewhere in your code the Event Handler is being called during the regular running of your JS, and not from the Outlook Client. (sometimes we see this happen if someone accidentally adds the parens to a function that they meant to refer to: Like 

`setTimeout(onNewMessageCompose(), 1000); `

**Comment by bogdanst24** [comment]
> When this happens is the Office.context.mailbox.item object also unavailable? (.item and .requirements get initialized around the same time, so that's why I'm asking...and failures in the item object would be much more severe)

I'm not sure as we are gracefully handling that scenario. Currently, we are only checking for the Office object, but will check for the item also. Makes sense either way as there is nothing to do without an Item. It will take a few days to get the information from production.

> Is there anyway you can post more of your code involving everywhere that references onNewMessageCompose and onMessageRecipientsChanged? Or maybe the full callstack of the exception unmodified?

I can share parts of the code, but this needs to be done privately and securely. Would giving you access to a private repo help? I also need to get it confirmed with our infosec,
Regarding the full callstack and unmodified exception, I'm not sure how to get that.

> Somewhere in your code the Event Handler is being called during the regular running of your JS, and not from the Outlook Client. (sometimes we see this happen if someone accidentally adds the parens to a function that they meant to refer to: Like
setTimeout(onNewMessageCompose(), 1000); 

We have something similar, but not exactly this. What we have is a retry mechanism because of some old bugs in Office JS, but the retry mechanism is part of the event. Something like:
```
onNewMessageCompose() {
   let promiseExecuted = false;
   
   execute.then(() => promiseExecuted = true)
               .catch( .....)
               .finally(() => event.completed({allowEvent: true}));
   
   setTimeout(() => {
      if (promsieExecuted) return;
      execute()
               .catch( .....)
               .finally(() => event.completed({allowEvent: true}));
   }, 5000);
}
```
However, I would expect that if this was a problem, the entire Office object would be unavailable? Will do some tests in the meantime

**Comment by timwan10** [comment]
If you can somehow reduce the problem down to a sample Add-in that you could share, that would be ideal, but I understand that this is difficult to repro. It's hard for us to investigate this without a repro though. I suspect that it's timing related due to it's inconsistent nature, so maybe playing with some timeouts to force the code a certain way could help? (or of there is something timing related, that could cause setIsSupported to be called before office OnReady/Initialize. 

But yeah the code that sets up Office.context.mailbox.item happens right before the code that sets up the requirements...so I would suspect that both of them aren't there if one of them isn't. 

I thought maybe that the callstack you posted before, had minimized code, but you may just be hitting the minimized office JS code...which there is no way to un minimize to debug in LaunchEvents right now :(

**Comment by bogdanst24** [comment]
Sorry for the late response. I missed the notification when you replied. I can't reproduce it; I can only see it through collected exceptions. I did some refactoring in December to get more detailed errors and tried to narrow the issue. What happens now is that there are no more issues of this type (isSetSupported), but instead, others appear. 

See for example https://github.com/OfficeDev/office-js/issues/5124. 

We now have many errors with the following, and I have no clue where or how to start solving them.

```
{"name":"InternalError","message":"The operation failed.","code":5009,"errorOrigin":"OfficeJS"}
```
```
{"name":"Internal Error","message":"An internal error has occurred.","errorOrigin":"OfficeJS"}
```
```
{"name":"InternalError","message":"The operation failed.","code":5001,"errorOrigin":"OfficeJS"}
```
```
{"name":"GenericResponseError","message":"An internal error has occurred.","code":9020,"errorOrigin":"OfficeJS"}
```
```
{"name":"HtmlSanitizationFailure","message":"The HTML santization has failed.","code":9011,"errorOrigin":"OfficeJS"}
```
```
{"name":"InternalError","message":"The operation failed.","code":2006,"errorOrigin":"OfficeJS"}
```
```
{"stack":"TypeError: Network request failed\n at foundation.win32.bundle:109:8714\n at foundation.win32.bundle:77:1244\n at k (foundation.win32.bundle:77:498)\n at Object.callTimers (foundation.win32.bundle:77:2655)\n at u.value (foundation.win32.bundle:35:3893)\n at foundation.win32.bundle:35:680\n at u.value (foundation.win32.bundle:35:2528)\n at u.value (foundation.win32.bundle:35:658)","message":"Network request failed"}
```
```
{"stack":"TypeError: Cannot read properties of undefined (reading 'l_ElevatedPermissionNeededForMethod_Text')\n    at H (C:\\Program Files\\Microsoft Office\\root\\Office16\\olk-launchevent-host.win32.bundle:26:16563)\n    at B (C:\\Program Files\\Microsoft Office\\root\\Office16\\olk-launchevent-host.win32.bundle:26:16734)\n    at Object.<anonymous> (C:\\Program Files\\Microsoft Office\\root\\Office16\\olk-launchevent-host.win32.bundle:26:48563)\n    at B (C:\\Users\\xxx\\AppData\\Local\\Microsoft\\Office\\16.0\\Wef\\{1E3AFBA5-5186-4F5B-8124-88DE902EA01F}\\pr9ED7GEjx9k2MFHsUYpcQ==\\Javascript\\5801732f-85b5-4ecb-9bd5-8e928c9088ca_1.0.0.15_es-ES\\bundle.js:1:45405)\n    at mt (C:\\Users\\xxx\\AppData\\Local\\Microsoft\\Office\\16.0\\Wef\\{1E3AFBA5-5186-4F5B-8124-88DE902EA01F}\\pr9ED7GEjx9k2MFHsUYpcQ==\\Javascript\\5801732f-85b5-4ecb-9bd5-8e928c9088ca_1.0.0.15_es-ES\\bundle.js:6:842)\n    at C:\\Users\\xxx\\AppData\\Local\\Microsoft\\Office\\16.0\\Wef\\{1E3AFBA5-5186-4F5B-8124-88DE902EA01F}\\pr9ED7GEjx9k2MFHsUYpcQ==\\Javascript\\5801732f-85b5-4ecb-9bd5-8e928c9088ca_1.0.0.15_es-ES\\bundle.js:7:16312\n    at Generator.next (<anonymous>)\n    at q (C:\\Users\\xxx\\AppData\\Local\\Microsoft\\Office\\16.0\\Wef\\{1E3AFBA5-5186-4F5B-8124-88DE902EA01F}\\pr9ED7GEjx9k2MFHsUYpcQ==\\Javascript\\5801732f-85b5-4ecb-9bd5-8e928c9088ca_1.0.0.15_es-ES\\bundle.js:7:15341)","message":"Cannot read properties of undefined (reading 'l_ElevatedPermissionNeededForMethod_Text')"}
```
```
{"message":"Unable to get property 'l_ElevatedPermissionNeededForMethod_Text' of undefined or null reference","description":"Unable to get property 'l_ElevatedPermissionNeededForMethod_Text' of undefined or null reference","number":-2146823281,"stack":"TypeError: Unable to get property 'l_ElevatedPermissionNeededForMethod_Text' of undefined or null reference\n   at H (Unknown script code:26:16555)\n   at B (Unknown script code:26:16726)\n   at Anonymous function (Unknown script code:26:48563)\n   at B (Unknown script code:1:45350)\n   at mt (Unknown script code:6:842)\n   at Anonymous function (Unknown script code:7:16309)\n   at Generator.prototype.next (native code)\n   at q (Unknown script code:7:15337)\n   at Yt (Unknown script code:10:37232)\n   at Anonymous function (Unknown script code:10:37491)"}
```

**Comment by karol-traczyk** [comment]
Hi MS Team,
Do you have any update on this issue? Since Friday we started to get a lot of reports from users leading to failing check `Office.context?.requirements?.isSetSupported('Mailbox', '1.3' )`. 
Before it was working fine, unfortunately I cannot reproduce it on my end.

**Comment by timwan10** [comment]
I unfortunately don't have an update here, aside from that the dev team is still trying to track this down on their side, but can't repro the issue. If there. @bogdanst24 For the errors you listed there, do you know the call that you made to cause those errors to be returned? Or is it just every API call that can potentially cause this? (in the other post you list Office.context.mailbox.item.to.getAsync())

**Comment by bogdanst24** [comment]
Most of the errors now are with 'l_ElevatedPermissionNeededForMethod_Text', either on   mailbox.item.notificationMessages.replaceAsync, or during the onMessageCompose, caught in a catch all condition. Not even sure where it comes from as almost everything is wrapped in a try catch and should be caught quickly

**Comment by bogdanst24** [comment]
For the 'l_ElevatedPermissionNeededForMethod_Text', I have a dedicated issue here https://github.com/OfficeDev/office-js/issues/5124
As shown on that issue, the problem is getting worse and worse.

**Comment by mhaatcbrain** [comment]
We are experiencing issues using Office.context.requirements.isSetSupported() as well. Both the requirements and item objects are set, but isSetSupported still returns undefined.

Our customers has only experienced the issue using Outlook 2024 though. In house we use Outlook 365 and do not experience the issue.

I hope you can help us fixing the issue :)

**Comment by timwan10** [comment]
This issue hasn't been fixed yet, but the root cause is the same as: https://github.com/OfficeDev/office-js/issues/5124 which is being updated with the latest progress. Closing out this issue and using the other issue to track progress on this.
