### ISSUE TITLE
ElevatedPermissionNeededForMethod error sometimes breaks event based logic in Outlook Desktop (old)

### ISSUE THREAD

**Issue by bogdanst24** [OfficeDev/office-js#5124]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC Desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook Desktop (old one)
* Office version number: Many, from 16.0.17531.20152 to 16.0.18227.20046
* Operating System: Windows
* Browser (if using Office on the web): -
 
## Expected behavior

Event-based add-ins are to work as expected, or a suggestive error will be thrown if errors are being made in code.

## Current behavior

Event-based actions such as OnNewMessageCompose or OnMessageRecipientsChanged, in Outlook Desktop (the old one), sometimes fail with **Unable to get property 'l_ElevatedPermissionNeededForMethod_Text' of undefined or null reference**. 
This issue is seen in our error logs for 3497 times in the past 7 days, 70 different customers. It is not always happening and cannot be reproduced by us or by the customers at request. 

## Steps to reproduce

Cannot reproduce.

# Provide additional details

1. The only other report around this is here https://github.com/OfficeDev/office-js/issues/2204 and it concluded with the usage of promises being the problem. We are indeed using promises, but at the same time the code is transpiled to ES16 and it works correctly in the majority of cases. There is even documentation about how to do it and I don't remember seeing anything about not using them anywhere. If this would be the case, we would need an official confirmation as it would basically require us to rewrite the entire project.

Example of usage:
```
export function getRecipients() {
  return new Promise<Office.EmailAddressDetails[]>((resolve, reject) => {
    const { mailbox } = Office.context;

    if (!mailbox.item) {
      reject(new Error('Unable to get recipients: No mailbox item'));
      return;
    }

    mailbox.item.to.getAsync({}, asyncResultCallback(resolve, reject));
  });
}


export function asyncResultCallback<ReturnType>(
  resolve: (value: ReturnType) => void,
  reject: (reason?: unknown) => void,
): (asyncResult: Office.AsyncResult<ReturnType>) => void {
  const { AsyncResultStatus } = Office;

  return ({ error, status, value, diagnostics }) => {
    if (status !== AsyncResultStatus.Succeeded) {
      reject({
        ...error,
        errorOrigin: 'OfficeJS',
        diagnostics: diagnostics as unknown,
      });
      return;
    }

    resolve(value);
  };
}

```
2. Not sure if related, but we are assigning a random GUID to all items and storing it as a custom property. Then, that id is passed in the error object. (We're doing this as in Outlook Dekstop the message ID is not available before the item is saved and we needed a method to correlate the different errors). For most of these exceptions, there is no ID. Could this be caused by a CustomPropertiesService issue? Obviously, we're first checking for an existing one. 
3. We have some reports from a customer experiencing this exception that the Web Add-in works for a few hours until at some point it crashes and then disappears from the Ribbon. Also, the events are not triggered anymore (as expected). Restarting Outlook solves the issue until it occurs again. Could this be related or help identity the cause?

## Useful logs

Examples of exceptions:
```
{"message":"Unable to get property 'l_ElevatedPermissionNeededForMethod_Text' of undefined or null reference","description":"Unable to get property 'l_ElevatedPermissionNeededForMethod_Text' of undefined or null reference","number":-2146823281,"stack":"TypeError: Unable to get property 'l_ElevatedPermissionNeededForMethod_Text' of undefined or null reference\n   at H (Unknown script code:26:16539)\n   at B (Unknown script code:26:16710)\n   at Anonymous function (Unknown script code:26:48768)\n   at Anonymous function (Unknown script code:1:45225)\n   at B (Unknown script code:10:38607)\n   at D (Unknown script code:1:45091)\n   at Jt (Unknown script code:1:51487)\n   at Anonymous function (Unknown script code:7:16682)\n   at Generator.prototype.next (native code)\n   at ot (Unknown script code:7:15145)"}
```

_Redacted the user name_
```
{"stack":"TypeError: Cannot read properties of undefined (reading 'l_ElevatedPermissionNeededForMethod_Text')\n    at H (C:\\Program Files\\Microsoft Office\\root\\Office16\\olk-launchevent-host.win32.bundle:26:16547)\n    at B (C:\\Program Files\\Microsoft Office\\root\\Office16\\olk-launchevent-host.win32.bundle:26:16718)\n    at Object.<anonymous> (C:\\Program Files\\Microsoft Office\\root\\Office16\\olk-launchevent-host.win32.bundle:26:48768)\n    at C:\\Users\\***\\AppData\\Local\\Microsoft\\Office\\16.0\\Wef\\{98C45364-3071-46B3-BD6B-422B61272356}\\Jte1SMcezEX_QO77B5Wo1g==\\Javascript\\5801732f-85b5-4ecb-9bd5-8e928c9088ca_1.0.0.14_en-US\\bundle.js:1:45254\n    at new Promise (<anonymous>)\n    at D (C:\\Users\\***\\AppData\\Local\\Microsoft\\Office\\16.0\\Wef\\{98C45364-3071-46B3-BD6B-422B61272356}\\Jte1SMcezEX_QO77B5Wo1g==\\Javascript\\5801732f-85b5-4ecb-9bd5-8e928c9088ca_1.0.0.14_en-US\\bundle.js:1:45091)\n    at Jt (C:\\Users\\***\\AppData\\Local\\Microsoft\\Office\\16.0\\Wef\\{98C45364-3071-46B3-BD6B-422B61272356}\\Jte1SMcezEX_QO77B5Wo1g==\\Javascript\\5801732f-85b5-4ecb-9bd5-8e928c9088ca_1.0.0.14_en-US\\bundle.js:1:51494)\n    at C:\\Users\\***\\AppData\\Local\\Microsoft\\Office\\16.0\\Wef\\{98C45364-3071-46B3-BD6B-422B61272356}\\Jte1SMcezEX_QO77B5Wo1g==\\Javascript\\5801732f-85b5-4ecb-9bd5-8e928c9088ca_1.0.0.14_en-US\\bundle.js:7:16694\n    at Generator.next (<anonymous>)\n    at ot (C:\\Users\\***\\AppData\\Local\\Microsoft\\Office\\16.0\\Wef\\{98C45364-3071-46B3-BD6B-422B61272356}\\Jte1SMcezEX_QO77B5Wo1g==\\Javascript\\5801732f-85b5-4ecb-9bd5-8e928c9088ca_1.0.0.14_en-US\\bundle.js:7:15149)","message":"Cannot read properties of undefined (reading 'l_ElevatedPermissionNeededForMethod_Text')"}
```

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by pepso** [comment]
We have a few hundreds of these per week for appointment fetching, and they seem to coalesce around HR users. We have assumed these are due to some "restricted" or "protected" configuration of their inboxes and/or appointment's attachments. 

However, we don't see the behavior that the add-in stops working/removed from ribbon, but this can be because the add-in sandbox is recreated between the appointment being opened/created.

It would be great to have an explanation what is the real cause of these so we know how to communicate this to our clients.

**Comment by bogdanst24** [comment]
@exextoc anything here?

**Comment by ztcdsb** [comment]
@pepso Can you create a separate post detailing the scenarios where add-in randomly disappearing? It is a quite a strange issue

**Comment by ztcdsb** [comment]
@bogdanst24 The failure here indicates that the add-in is calling an API that requires a permission higher than what is specified in the manifest. Let me try repro this and I will share my findings here

**Comment by bogdanst24** [comment]
It happens randomly for random users. I was never able to reproduce it, but I can see it happening daily for hundreds of users

**Comment by bogdanst24** [comment]
@ztcdsb since January 21st we are getting more and more errors like the one supported. It is continuously increasing. It went from 500 errors a day to more than 5000 yesterday (10 times)

**Comment by barisbikmaz** [comment]
We are seeing this a lot in the classic Outlook version Semi Annual version 16.0.17328.20550 on Windows now. The other platforms are fine.
Since 10th of Januar this error increased a lot, about few thousand a day.

We could track it down to the place where I try to get the session data, so the call sessionData.getAsync seems to raise this error but we are not sure, because we can't really reproduce.

I tried to analyze the olk-launchevent-host.win32.bundle and from what I understand the permissionLevel check for  sessionData.getAsync fails. But in our manifest we have ReadWrite permissions.

The full error

{"name":"TypeError","message":"Unable to get property 'l_ElevatedPermissionNeededForMethod_Text' of undefined or null reference","stack":"TypeError: Unable to get property 'l_ElevatedPermissionNeededForMethod_Text' of undefined or null reference\n   at N (Unknown script code:26:15684)\n   at k (Unknown script code:26:15855)\n   at hi (Unknown script code:26:71751)\n   at Anonymous function (Unknown script code:141:105496)\n   at f (Unknown script code:68:207)\n   at v (Unknown script code:68:1590)\n   at c (Unknown script code:68:433)\n   at Anonymous function (Unknown script code:141:105462)\n   at Generator.prototype.next (native code)\n   at Anonymous function (Unknown script code:1:1247)"}

The Anonymous function (Unknown script code:141:105496) line is the call to sessionData.getAsync.
The other lines from the call stack are from an internal script, probably the olk-launchevent-host.win32.bundle where we found the error message.

**Comment by ztcdsb** [comment]
Thanks for reporting this issue. It has been put on our backlog. We unfortunately have no timelines to share at this point 

Internal tracking id: Office: 9807892

**Comment by bogdanst24** [comment]
@ztcdsb we have more than 100 customers experiencing this issue. Please prioritize or let us know if there is any workaround available. This is a really big problem.

**Comment by barisbikmaz** [comment]
@ztcdsb 
We tried to ignore Session Errors but the fix did not help. The error raise now on a different code location, I assume each time when trying to get sth from the mailbox item. Below our current error stats. We still can't reproduce it on our side, but it seems to do sth with the rights on the manifest.


![Image](https://github.com/user-attachments/assets/6cba095b-0706-4962-88a3-7fdc9ad1997d)

**Comment by bogdanst24** [comment]
Most of the issues are now coming from 16.0.17928.20392
On our side:

![Image](https://github.com/user-attachments/assets/2dd69dfd-e5ff-4cbf-9e65-6b49fd16846d)

**Comment by JJSaysNay** [comment]
> Thanks for reporting this issue. It has been put on our backlog. We unfortunately have no timelines to share at this point
> 
> Internal tracking id: Office: 9807892

This needs to be prioritized.

**Comment by ztcdsb** [comment]
@bogdanst24 @barisbikmaz I'm still investigating the root cause, but without a reliable repro, it's been difficult to pinpoint the issue. Have you discovered anything new about the bug recently that might help us narrow it down?

**Comment by barisbikmaz** [comment]
@ztcdsb We still cannot reproduce it locally but we are still seeing this error a lot. Is there any information we could provide to help you in this case? It seems like it does not happen everytime it could be the first time when opening Outlook because we mostly see the error in the mornings.

**Comment by bogdanst24** [comment]
@barisbikmaz are you also using promises? I'm thinking about rewriting everything without, but that is no low effort and I have no guarantee that is going to fix the issue.

**Comment by barisbikmaz** [comment]
@bogdanst24 Yes we are using a lot of promises. But most of the time the addin works. Why do think it has sth to do with promises? Timing issues?

**Comment by ztcdsb** [comment]
@barisbikmaz @bogdanst24 Thanks for sharing the details again. Even though we haven't posted anything here, please know that we're still actively working on resolving this issue. We'll be releasing additional logging options soon help with easier debugging, hopefully those will help capture more detailed logs on your end.

In the meantime, we're also trying to repro the issue internally, and please feel free to share any new findings here as well

**Comment by touss59** [comment]
Hi @ztcdsb,

Do you have any updates on this bug?
Approximately 5% of our users have been experiencing this issue since February.
The problem occurs when calling the following APIs:
- `Office.context.mailbox.item.subject.getAsync`
- `Office.context.mailbox.item.notificationMessages.replaceAsync`

This issue occurs only in Classic Outlook on Windows and is most commonly observed with Office versions starting with 16.0.17928*, though it can occur in other versions as well.

Please let me know if you need any additional information.

**Comment by ztcdsb** [comment]
@touss59 Hi, are you still encountering the issue? If so, could you please share more details, such as the steps to reproduce it or a code snippet? That would help us investigate more effectively.

**Comment by ztcdsb** [comment]
@touss59 Unfortunately, we haven't been able to reproduce the issue on our end. It would be very helpful if you could provide a consistent repro scenario so we can investigate further. In the meantime, we're also continuing our efforts to reproduce it internally

**Comment by bogdanst24** [comment]
Do not close.

**Comment by touss59** [comment]
@ztcdsb We are also unable to reproduce the issue

**Comment by kwame-ansong** [comment]
@bogdanst24, we are currently adding logs to help us better understand this issue since we are unable to reproduce it in-house.

**Comment by bogdanst24** [comment]
Are these internal logs that you already have access to, or do I need to take any action?

**Comment by kwame-ansong** [comment]
These logs will be internal, and they will also be available as runtime logs for any impacted user.
I don't think you need to take any action here unless an impacted user sends you their runtime logs.

**Comment by ValToussUpSlide** [comment]
For your information, recently some of our users with the version “16.0.18526.20634", 16.0.19127.20314” experienced this bug.

**Comment by bogdanst24** [comment]
Number of errors we collect with ElevatedPermissionNeededForMethod, daily, count by version. 

<img width="998" height="617" alt="Image" src="https://github.com/user-attachments/assets/6963da06-8dec-44e9-9164-3d92e12563c7" />

**Comment by ivanosevitch** [comment]
We are still seeing numerous such errors (Cannot read properties of undefined (reading 'l_ElevatedPermissionNeededForMethod_Text') from several Outlook API calls on Outlook Classic Windows versions:
- 16.0.19530.20144
- 16.0.19530.20184

Somehow there was big reduction of errors between November 27th 2025 and January 23rd, but errors have come back in full force.
We are still unable to reproduce it either.

**Comment by ivanosevitch** [comment]
Looking at `C:\Program Files\Microsoft Office\root\Office16\olk-launchevent-host.win32.bundle` where the error originates, it appears there are 2 distinct Outlook issues:
 
## Permission issue

This is the most critical one.
We have deployed a manifest with `<Permissions>ReadWriteItem</Permissions>`, but the following APIs fail on Outlook Classic (for some users and only some of the time) with the error `Cannot read properties of undefined (reading 'l_ElevatedPermissionNeededForMethod_Text')`:
   - `Office.context.mailbox.item.body.getTypeAsync`
   - `Office.context.mailbox.item.body.setSignatureAsync`
   - `Office.context.mailbox.item.notificationMessages.replaceAsync`
   - `Office.context.mailbox.item.subject.getAsync`

It seems as though the user only has "restricted" permissions, though we explicitly ask for "read write item" in the manifest.

## Bad error logging
This one is less annoying but fixing it could provide better error messages.
In `launchevent-host.win32.bundle` there is this bit of (minified) code:
```js
    var W;
    function q(e) {
      return W[e];
    }
    var V;
    function J(e, t) {
      if (-1 == D())
        throw (function (e) {
          return j(
            "Invalid operation ({0}) when Office.context.mailbox.item is null.".replace(
              "{0}",
              e,
            ),
          );
        })(t);
      if (D() < e)
        throw j(
          q("l_ElevatedPermissionNeededForMethod_Text").replace("{0}", t),
        );
    }
```
However, `W` only seems to be declared but never initialized. This means that `q("l_ElevatedPermissionNeededForMethod_Text")` will _always_ throw (with  `Cannot read properties of undefined (reading 'l_ElevatedPermissionNeededForMethod_Text')`), because `W` is undefined.

**Comment by ValToussUpSlide** [comment]
@ztcdsb @exextoc  We were able to reproduce the issue internally using Outlook’s classic Mail Merge feature for bulk emails.

**Comment by bogdanst24** [comment]
Any attention here? I just checked and we had 204648 such errors in the past 30 days

Examples

```
- {"stack":"TypeError: Cannot read properties of undefined (reading 'l_ElevatedPermissionNeededForMethod_Text')\n at q (<ANONYMIZED_PATH> Files\\Microsoft Office\\<ANONYMIZED_NETWORK_PATH>:26:16141)\n at J (<ANONYMIZED_PATH> Files\\Microsoft Office\\<ANONYMIZED_NETWORK_PATH>:26:16312)\n at Object.<anonymous> (<ANONYMIZED_PATH> Files\\Microsoft Office\\<ANONYMIZED_NETWORK_PATH>:26:51130)\n at M (<ANONYMIZED_PATH>:1:29162)\n at St (<ANONYMIZED_PATH>:6:1094)\n at <ANONYMIZED_PATH>:7:20786\n at Generator.next (<anonymous>)\n at Z (<ANONYMIZED_PATH>:7:19441)","message":"Cannot read properties of undefined (reading 'l_ElevatedPermissionNeededForMethod_Text')"}
```

```
- {"stack":"TypeError: Cannot read properties of undefined (reading 'l_ElevatedPermissionNeededForMethod_Text')\n at q (<ANONYMIZED_PATH> Files\\Microsoft Office\\<ANONYMIZED_NETWORK_PATH>:26:16141)\n at J (<ANONYMIZED_PATH> Files\\Microsoft Office\\<ANONYMIZED_NETWORK_PATH>:26:16312)\n at Object.<anonymous> (<ANONYMIZED_PATH> Files\\Microsoft Office\\<ANONYMIZED_NETWORK_PATH>:26:50865)\n at L (<ANONYMIZED_PATH>:1:29807)\n at Ot (<ANONYMIZED_PATH>:6:1365)\n at <ANONYMIZED_PATH>:7:20415\n at Generator.next (<anonymous>)\n at Z (<ANONYMIZED_PATH>:7:19441)","message":"Cannot read properties of undefined (reading 'l_ElevatedPermissionNeededForMethod_Text')"}
```
