### ISSUE TITLE
Word add-in: DevicePermission.requestPermissions(..) throws "Cannot read properties of undefined (reading 'EN-US')"

### ISSUE THREAD

**Issue by senthilSaras** [OfficeDev/office-js#5167]
I'm trying to request microphone permission for my Word add-in. When making the request, the following exception is thrown:

message: "Cannot read properties of undefined (reading 'EN-US')"
stack: "TypeError: Cannot read properties of undefined (reading 'EN-US')    
at t._getDefaultValue
at t.getAddinDisplayName    
at vx.requestPermissions

## Sources
1. https://res-1.cdn.office.net/officeonline/hashed/2b29882a809cf6b3/osfruntimewordwac.js
2. https://res-1.cdn.office.net/officeonline/hashed/aad04e477ed1316f/wordeditords.box4.dll3.js
3. Add-in code that makes requestPermissions call (this is taken from DevicePermissions documentation)
  // Request permission from a user to access their microphone.
  if (Office.context.platform === Office.PlatformType.OfficeOnline) {
    const deviceCapabilities = [Office.DevicePermissionType.microphone];
    Office.devicePermission
      .requestPermissions(deviceCapabilities)
      .then((isGranted) => {
        if (isGranted) {
          console.log("Permission granted.");
          // Reload your add-in before you run code that uses the device capabilities.
          location.reload();
        } else {
          console.log("Permission has been previously granted and is already set in the iframe.");
          // Since permission has been previously granted, you don't need to reload your add-in.
        }
      })
      .catch((error) => {
        console.error("Permission denied.", error);
      });
  }

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: Microsoft 365
* Operating System: Windows 10
* Browser (if using Office on the web): Edge
 
## Expected behavior
Office.devicePermission.requestPermissions(..) to throw a modal dialog.

## Current behavior
Office.devicePermission.requestPermissions() throws the above exception (and modal dialog isn't presented).

## Steps to reproduce
1. Open Word on Web
2. Install https://appsource.microsoft.com/en-us/product/office/WA200006533?tab=Overview
3. Click "Start Recording"

## Link to live example(s)
See above

# Provide additional details
See below for call stack/stack trace.
![stack](https://github.com/user-attachments/assets/5d61ef23-9fca-4925-a91a-b58027775a2d)

In stepping through wordeditords.box4.dll3.js and osfruntimewordwac.js, I see that requestPermissions function is trying to get addin' display name by calling getAddinDisplayName. However, addinDisplayNames property is not present and thus an exception is thrown.

t.prototype.getAddinDisplayName = function() {
                return this._getDefaultValue(this._addinDisplayNames)
            }

Upon code inspection, it appears that _addinDisplayNames is set only in "return new OSF.Manifest.Manifest(..)". So, I'm inferring that Manifest(..) is somehow not called for my add-in. This is corroborated by absence of _alternateId, _signature and _capabilities properties (these properties are also set in the Manifest() function). Having said that, I'm not sure why Manifest(..) isn't being invoked. 

this: t
        _UILocale: "EN-US"
        _allowSnapshot: true
        _defaultLocale: "en-US"
        _descriptions: {en-US: 'For accurately transcribing your voice message.'}
        _displayNames: en-us: "Voice to Text"
        <snip>

FWIW, _displayNames property is indeed present and set correctly. Could getDefaultDisplayName() be used instead of getAddinDisplayName()?

If there's something I can/should fix or workaround at my end, happy to do so (pointers would be appreciated).

## Context
Our users can't use the add-in in "Office on the Web". It is critical for them to use the microphone (otherwise there is limited value from the add-in)

**Comment by RuizhiSunMS** [comment]
Hi @senthilSaras, thx for reaching out here.
May I ask that what's the meaning of 'login to word' in repro steps? Is this 'sign out'?
![image](https://github.com/user-attachments/assets/56468046-d42f-497c-a366-ceff9f5cb837)

**Comment by senthilSaras** [comment]
Hi @RuizhiSunMS  Please ignore "login to Word" (as that step is not applicable to "Office on the Web" scenario). I've removed that step from "Steps to reproduce". Thanks for looking at this!

**Comment by RuizhiSunMS** [comment]
Hi @senthilSaras,
Then may I ask what did you see after clicking 'start recording'? I tried all these three buttons but got nothing. I also checked the console and network in f12. Console had nothing while Network showed like the below.
![image](https://github.com/user-attachments/assets/477390c3-378b-4abe-b11c-00d784d6c837)

**Comment by senthilSaras** [comment]
Clicking “start recording” should result in a modal dialog. Due to this issue, console shows failure (can you please switch to Console from Network).

just to be sure, this is Word on the Web right? And you’re trying from a browser like Edge on Windows 10?

thanks

**Comment by RuizhiSunMS** [comment]
![image](https://github.com/user-attachments/assets/f16a2d89-6472-4af7-9dc6-fd64072d4733)
Clicked 'start recording' times by times but found nothing. Neither the console.
I'm using edge 131.0.2903.70

**Comment by senthilSaras** [comment]
That is very weird. I was able to reproduce what you're observing when user has not logged in (see attached picture). Can you please make sure you're logged in?

![image](https://github.com/user-attachments/assets/10339338-3402-4bb8-8d6f-c9bc40dbfb61)

If you're logged in and still seeing issues, is there another way to provide repro steps?

**Comment by RuizhiSunMS** [comment]
@senthilSaras, I'm signed in. You mean this case would repro when signed out?

**Comment by senthilSaras** [comment]
Sorry. Let me clarify - I thought you were not signed in. Looking at my code, there should be spew in the console if you had not signed in (and that's not seen either indicating some other issue). 

I'm not sure why the add-in is not working on your machine. Do you have another machine? Or can I give you repro steps some other way?

**Comment by RuizhiSunMS** [comment]
Hi @senthilSaras, sorry for forgetting to tell you that, my colleage @guoms1 tried it as well on his device and we share the same behavior. 
May I confirm with you that:
1. signed in or signed out point to 'sign in Word' rather than 'sign in to this addin' (we don't find any place to sign in to the addin)
2. 'signed in' is correct.
3. once you clicked the button, console would pop out such error msg. '
4. the image you shared in description is all you got in console (please paste a full, text version rather than screenshot)
5. is there anything network call happening in clicking button (from our sides, we found none). If yes, please share the session id

**Comment by senthilSaras** [comment]
1. Correct, sign into Word
2. Correct
3. Correct
4. Here you go: 

word-web-16.00.js:25  [Violation] Permissions policy violation: microphone is not allowed in this document.
MediaDevices.getUserMedia @ word-web-16.00.js:25
(anonymous) @ taskpane.ts:161
(anonymous) @ taskpane.js:1
(anonymous) @ taskpane.js:1
(anonymous) @ taskpane.js:1
o @ taskpane.js:1
T @ taskpane.js:1
taskpane.ts:149  Permission denied. RichApi.Error: Cannot read properties of undefined (reading 'EN-US')
    at new n (word-web-16.00.js:25:340728)
    at r.processRequestExecutorResponseMessage (word-web-16.00.js:25:405890)
    at word-web-16.00.js:25:403951
(anonymous) @ taskpane.ts:149
Promise.catch
(anonymous) @ taskpane.ts:148
(anonymous) @ taskpane.ts:158
(anonymous) @ taskpane.js:1
(anonymous) @ taskpane.js:1
(anonymous) @ taskpane.js:1
o @ taskpane.js:1
T @ taskpane.js:1
taskpane.ts:186  Error accessing microphone: NotAllowedError: Permission denied

5. Yes. I see something like "usid=9714bef8-d4da-2b36-8638-aca72b05a5bd". If it is something else, please let me know how to get that for you.

**Comment by RuizhiSunMS** [comment]
@senthilSaras, one more q, please paste this issue's impact.
Add more new feedback from our side:
I got another colleague and he can't repro as well. Unable to repro is still the main block. 
Here I have other questions:
1. does it work on desktop? (not work at my desktop)
2. we three tried to click all buttons. No responding at all. Should it do something?
3. do you have any users who can repro it? What kind of account they (and you) use?

**Comment by senthilSaras** [comment]
1. Yes it works on Desktop (there are thousands of monthly users of this add-in)
2. Yes. Clicking on "Start Recording" should start the audio recording (and you can start talking). "Stop Recording" should stop the audio recording. "Upload Recording" allows you to upload an audio file for transcription
3. Yes. I've tried with both my hotmail.com as well as corporate account.

**Comment by senthilSaras** [comment]
@RuizhiSunMS @guoms1 I was able to craft a very targeted repo. I believe there's some incompatibility between keyboard shortcuts and device permission features.

1. Clone this repo locally. https://github.com/OfficeDev/Office-Add-in-samples/tree/main/Samples/office-keyboard-shortcuts 
2. Add the following to src\taskpane.js. And, call requestPermissionsOfficeOnline() from Office.onReady(). 

function requestPermissionsOfficeOnline() {
  // Request permission from a user to access their microphone.
  if (Office.context.platform === Office.PlatformType.OfficeOnline) {
    const deviceCapabilities = [Office.DevicePermissionType.microphone];
    Office.devicePermission
      .requestPermissions(deviceCapabilities)
      .then((isGranted) => {
        if (isGranted) {
          console.log("Permission granted.");
          // Reload your add-in before you run code that uses the device capabilities.
          location.reload();
        } else {
          console.log("Permission has been previously granted and is already set in the iframe.");
          // Since permission has been previously granted, you don't need to reload your add-in.
        }
      })
      .catch((error) => {
        console.error("Permission denied.", error);
        // For now, letting getUserMedia() to fail and let error be reported through it
        // for simplicity (across Desktop and Web scenarios)
      });
  }
}

3. Side-load the add-in to Word on the Web by following steps in https://github.com/OfficeDev/Office-Add-in-samples/tree/main/Samples/office-keyboard-shortcuts#run-the-sample-from-localhost
4. Open the add-in. Go to Console and you should see the following

 taskpane.js:105  Permission denied. RichApi.Error: Cannot read properties of undefined (reading 'EN-US')
    at new n (word-web-16.00.js:25:340728)
    at r.processRequestExecutorResponseMessage (word-web-16.00.js:25:405890)
    at word-web-16.00.js:25:403951

FWIW, I'm observing this on Edge (Version 131.0.2903.86 (Official build) (64-bit)) on Windows 11.

**Comment by senthilSaras** [comment]
@RuizhiSunMS @guoms1 Could you please take a look again?

**Comment by guoms1** [comment]
Dear @senthilSaras 

Thank you for your patience, and I apologize for the delay in resolving this issue. I understand the frustration caused by the lack of follow-up on your initial report and the repro method you provided three weeks ago.

I want to assure you that I am now actively looking into this and will prioritize finding a solution. I will review the details and get back to you with an update on the progress within the a couple of business days.

If you have any further insights or details you’d like to share, please don’t hesitate to reach out. Your feedback is invaluable, and I am committed to resolving this issue as quickly as possible.

Thank you again for your understanding, and I will be in touch soon.

Best regards,

**Comment by senthilSaras** [comment]
Thanks for the update, @guoms1

**Comment by guoms1** [comment]
I can follow the steps you provided to reproduce this issue. Moving forward, I will involve the relevant experts to conduct further investigation.

#9606236 is used for tracking this issue.

Thanks,

**Comment by senthilSaras** [comment]
Great, thanks @guoms1  for reproducing this issue! Looking forward to a resolution soon.

**Comment by senthilSaras** [comment]
@guoms1 Any news on a fix for this issue?

**Comment by guoms1** [comment]
Hi, @senthilSaras,

Thank you for reaching out regarding the status of your reported issue. I understand that this has been ongoing for some time, and I truly appreciate your patience.

After our initial investigation, we found that this issue falls under the scope of another team. We've escalated it to the appropriate group, and they have assigned a dedicated resource to investigate further. Given that this involves cross-team collaboration, the process has taken longer than expected. However, I want to assure you that the issue is being actively worked on.

Best regards,

**Comment by senthilSaras** [comment]
@guoms1 Thanks for your response. Appreciate the transparency. Please keep me posted on the ETA.

**Comment by mayurandhare13** [comment]
@senthilSaras Fix has been pushed. But, yet to deploy to Production. Hopefully by next week, it will be in Prod. I'll post the once fix reaches to Prod.

**Comment by senthilSaras** [comment]
That's great news, thanks @mayurandhare13 .  Looking forward to see the fix rolled out and unblock customers.

**Comment by mayurandhare13** [comment]
@senthilSaras I verified changes in Prod. Could you please check if this is working for you.

**Comment by senthilSaras** [comment]
@mayurandhare13 Works for me as well. Thanks a bunch!
