### ISSUE TITLE
[Word][Office Dialog] Office dialog does not send an event if it closed by ESC key

### ISSUE THREAD

**Issue by shinji-morimitsu** [OfficeDev/office-js#5200]
# Provide required information needed to triage your issue

Office Dialog (Office.context.ui.displayDialogAsync) does not fire an event, if it is closed by ESC key.

Note:
If it is closed by Alt-F4 or right-top 'X' button, `{"type":"dialogEventReceived","error":12006}` is recieved.

## Your Environment

* Platform : PC desktop
* Host : Word
* Office version number: 2501 (Build 18407.20002)
* Operating System: Windows 11
* Browser (if using Office on the web): ______
 
## Expected behavior

Office.EventType.DialogEventReceived is fired.

## Current behavior

No event is triggered.

## Steps to reproduce

1. Paste 'live example' code in script lab
2. run
3. Touch ESC key for dialog

## Link to live example(s)

```
async function run() {
  Office.context.ui.displayDialogAsync(
    'https://script-lab.public.cdn.office.net/script-lab/',
    { height: 30, width: 30, displayInIframe: true, promptBeforeOpen: false },
    ({ value }) => {
      console.log(`callback is called`);
      value.addEventHandler(
        Office.EventType.DialogMessageReceived,
        ({ message }: { message: string; origin: string | undefined }) => {
          console.log(`message: ${JSON.stringify(message)}`);
        },
      );
      value.addEventHandler(
        Office.EventType.DialogEventReceived, (event: { error: number }) => {
          console.log(`event: ${JSON.stringify(event)}`);
        }
      );
    }
  );
}
```

# Provide additional details

1. ______
2. ______
3. ______

## Context

Actually, we display dismisser while dialog opens, so it becomes terrible state if dialog is closed without events.

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by DominikDoom** [comment]
I was just about to write a similar issue myself.

We also recently encountered this bug in our Outlook Addin on Classic Outlook for Windows. The dialog sends no close event and also seems to not clear itself up properly if closed via ESC. This is really bad as we open ours from the task pane, meaning that even though the popup was closed, the API refuses to open a new one since only one at a time is allowed. The user has to completely close and reopen the task pane (killing the underlying webview process) to be able to open the dialog again.

It seems to be the same issue already discovered years ago in #9, and still not fixed to this day.

Additional observations:
- It works correctly in the web, so i suspect the issue is the Win32 clients don't release the popup window's resources correctly after ESC, leading to undefined behavior.
- Killing the addin's webview process in the task manager also fixes the bugged state, similar to closing and reopening the task pane. Reloading the webview page doesn't.
- From a bit of logging:
![image](https://github.com/user-attachments/assets/d5ea1fe6-2fdc-43d3-b928-45046faef234)

**Comment by RuizhiSunMS** [comment]
Hi @shinji-morimitsu and @DominikDoom, thx for reaching out here. Will involve experts to investigate.

**Comment by RuizhiSunMS** [comment]
Hi @DominikDoom and @shinji-morimitsu, would you please provide the business impact of this case (how many users of yours get affected for example)? It's necessary for us to transfer it to the owning team.

**Comment by DominikDoom** [comment]
@RuizhiSunMS I can't give you an actual number as the add-in is still under development to replace our older COM add-in. The company I work for is providing mail archiving solutions for enterprise customers, and the add-in is for quick access to those archived mails and working with them in Outlook. The dialog is used to show a preview of the archived mail/document since the task pane is usually too small for that, so it can easily happen during regular use. From the perspective of the user, the add-in seems to stop working randomly (and we have no way to differentiate this bug from an actual dialog still being open to provide UX hints), which would also put a large burden on our customer support or make us look unprofessional, so it is a critical issue for us. A rough guess would be at least 10k affected end users across different enterprises worldwide as the dialog system is a fairly common part of the workflow in our example.

Just for clarification: I and my company's product are unrelated to @shinji-morimitsu, it was just by coincidence that we noticed this issue at almost the same time. Our Addin will only release for Outlook, but since @shinji-morimitsu noticed it in Word, the issue probably happens in all office apps using the dialog API.

**Comment by shinji-morimitsu** [comment]
@RuizhiSunMS 
We are releasing two add-ins, either of which will reproduce I think we have about 500 users in total.
For add-ins that require login and also support SSO, I believe that the login window can only be implemented in Office Dialog. Therefore, the impact should be quite large.

https://appsource.microsoft.com/en-us/product/office/WA104382068?tab=Overview
https://appsource.microsoft.com/en-us/product/office/WA200006758?tab=Overview

**Comment by kefalak** [comment]
This was indeed an issue years ago, at some point it must have been fixed, because while I was using an add-in some months ago, closing with ESC key was firing an event and I was capturing it. It seems the the problem somehow resurfaced recently and I am also impacted by it. Just a wild guess, but it could be related to this error being thrown every time a dialog is displayed:

Uncaught TypeError TypeError: Cannot read properties of undefined (reading 'register')
    at <anonymous> (appsforoffice.microsoft.com/lib/1/hosted/excel-win32-16.01.js:25:344051)
    at <anonymous> (appsforoffice.microsoft.com/lib/1/hosted/excel-win32-16.01.js:25:1421923)
    --- Promise.then ---
    at <anonymous> (appsforoffice.microsoft.com/lib/1/hosted/excel-win32-16.01.js:25:1421865)
    at <anonymous> (appsforoffice.microsoft.com/lib/1/hosted/excel-win32-16.01.js:25:1439778)
    at t (appsforoffice.microsoft.com/lib/1/hosted/excel-win32-16.01.js:25:1443690)
    at <anonymous> (appsforoffice.microsoft.com/lib/1/hosted/excel-win32-16.01.js:25:1443703)
    at <anonymous> (appsforoffice.microsoft.com/lib/1/hosted/office.js:76:26318)
    at t (appsforoffice.microsoft.com/lib/1/hosted/office.js:76:25719)
    at <anonymous> (appsforoffice.microsoft.com/lib/1/hosted/office.js:76:32294)
    at c (appsforoffice.microsoft.com/lib/1/hosted/office.js:76:4670)
    at <anonymous> (appsforoffice.microsoft.com/lib/1/hosted/office.js:76:4759)
    at j (appsforoffice.microsoft.com/lib/1/hosted/office.js:76:31700)
    at <anonymous> (appsforoffice.microsoft.com/lib/1/hosted/excel-win32-16.01.js:25:253606)
    at <anonymous> (appsforoffice.microsoft.com/lib/1/hosted/office.js:76:32852)
    at <anonymous> (appsforoffice.microsoft.com/lib/1/hosted/office.js:76:5641)
    at <anonymous> (appsforoffice.microsoft.com/lib/1/hosted/office.js:76:4824)
    at <anonymous> (appsforoffice.microsoft.com/lib/1/hosted/office.js:76:32745)
    at <anonymous> (appsforoffice.microsoft.com/lib/1/hosted/excel-win32-16.01.js:25:115794)
    at E (appsforoffice.microsoft.com/lib/1/hosted/office.js:76:29113)
    at s (appsforoffice.microsoft.com/lib/1/hosted/office.js:76:30981)
    at c (appsforoffice.microsoft.com/lib/1/hosted/office.js:76:4670)
    at <anonymous> (appsforoffice.microsoft.com/lib/1/hosted/office.js:76:4759)
    at y (appsforoffice.microsoft.com/lib/1/hosted/office.js:76:33806)
    at m (appsforoffice.microsoft.com/lib/1/hosted/office.js:76:6822)
    --- load ---
    at <anonymous> (appsforoffice.microsoft.com/lib/1/hosted/office.js:76:7200)
    at <anonymous> (appsforoffice.microsoft.com/lib/1/hosted/office.js:76:4475)
    at H (appsforoffice.microsoft.com/lib/1/hosted/office.js:76:34335)
    at <anonymous> (appsforoffice.microsoft.com/lib/1/hosted/office.js:76:35080)
    at <anonymous> (appsforoffice.microsoft.com/lib/1/hosted/office.js:76:35935)

**Comment by dcallahan11** [comment]
Has there been any further update or resolution here? We're running into the same issue as well. I believe @DominikDoom did a good job of outlining the specific issue. When our user's close out of the dialog window using the "Escape" key, it doesn't appear that any event is raised, causing our task pane to hang indefinitely on a loading page unless the user restarts the add in application altogether.

**Comment by slabereemsft** [comment]
@EsterBergen - This is tracked with internal id - 9630859.

**Comment by demyte** [comment]
@slabereemsft @EsterBergen 

We are seeing an issue (that looks to be the same as this) with the user closing via ESC (this is in Excel) where when we try to open another dialog after this has happened we get:

![Image](https://github.com/user-attachments/assets/d29119ea-675c-47bb-9b17-7a746dc4b5d8)

**Note:**  
For us, this only seems to happen in the desktop client, not the web client.

**Comment by timwan10** [comment]
Of note, this is also happening in Outlook. (and I suspect all clients that call displayDialogAsync)

**Comment by cornflakeboy** [comment]
I can confirm, that this happens in Excel as well. Is there any hope for a fix? Our company has a large user base which is annoyed by this issue.

**Comment by demyte** [comment]
@slabereemsft @EsterBergen 

Are we able to get some visibility on when this is going to be fixed as its a continual pain for our users and our support to have to talk through the issue and how to resolve it, it is just wasting everyones time.

It also reflects badly on our product as the users see it as our failure with no fix being made.

I have tried to trap the ESC key with a keydown handler at the window/document level, but this seems to be ignored.

Honestly, if the fix was to make ESC do nothing, I would be very happy.

Thanks.

**Comment by bigelowt** [comment]
@demyte, 100% agree, hitting ESC on a dialog should not put an Add-in in a state where a restart of PowerPoint/Word/Etc. is required to open another dialog.  FYI, ESC key on the Mac works as expected, closes dialog and user can re-open a dialog.  ESC key Online does nothing.  Either of these two behaviors would be much appreciated.

BTW, this has been an issue for quite some time...

https://github.com/OfficeDev/office-js/issues/9

Thanks

**Comment by EsterBergen** [comment]
Hi @bigelowt , @demyte and @cornflakeboy - There is a fix that recently went in and should roll out soon.  We'll provide an update when we see the build in production for you to check. Thanks for your patience.

**Comment by browningjp** [comment]
@EsterBergen we are facing the same issue. Has there been any progress on the rollout of a fix? Thanks

**Comment by trumully** [comment]
This issue is still observed for our Excel add-in. We now use [`window.open`](https://developer.mozilla.org/en-US/docs/Web/API/Window/open) which does not have this issue and has the capacity to communicate information between the window and a workbook. Is there any issue using this over `displayDialogAsync`?

**Comment by demyte** [comment]
This is resolved for me now - I am on this version.

![Image](https://github.com/user-attachments/assets/531f61c8-b3e0-412a-9399-5bbb4a308c58)

**Comment by DominikDoom** [comment]
Can confirm it's fixed for us in Outlook too - also on Version 2503 Build 18623.20208

**Comment by bigelowt** [comment]
Can confirm this is fixed in PowerPoint Version 2503 Build 16.0.18623.20116.

Thanks!

Troy
