### ISSUE TITLE
Worksheet.copy() does not work with "Before" or "After"

### ISSUE THREAD

**Issue by AlexJerabek** [OfficeDev/office-js#775]
## Expected Behavior
I expect the specified worksheet will be copied before or after itself.

## Current Behavior
I get an InvalidArgument Error.

## Steps to Reproduce, or Live Example
https://gist.github.com/AlexJerabek/05bc3be21d6a0d9986b2bdd7538675d7

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: PC Desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 1911
* Operating System: Win 10
* Browser (if using Office Online): N/A

## Useful logs
[ERROR]: Error:
{
    "description": "The argument is invalid or missing or has an incorrect format.",
    "message": "The argument is invalid or missing or has an incorrect format.",
    "stack": "InvalidArgument: The argument is invalid or missing or has an incorrect format.\n   at Anonymous function (https://appsforoffice.microsoft.com/lib/1/hosted/excel-win32-16.01.js:24:282519)\n   at o (https://script-lab-react-runner-beta.azurewebsites.net/static/js/1.30a5fcfe.chunk.js:1:2779072)\n   at Anonymous function (https://script-lab-react-runner-beta.azurewebsites.net/static/js/1.30a5fcfe.chunk.js:1:2779219)\n   at u (https://script-lab-react-runner-beta.azurewebsites.net/static/js/1.30a5fcfe.chunk.js:1:314565)",
    "name": "RichApi.Error",
    "code": "InvalidArgument",
    "traceMessages": [],
    "innerError": null,
    "debugInfo": {
        "code": "InvalidArgument",
        "message": "The argument is invalid or missing or has an incorrect format.",
        "errorLocation": "Worksheet.copy",
        "statement": "var copy=activeWorksheet.copy(...);",
        "surroundingStatements": [
            "var workbook=context.workbook;",
            "var worksheets=workbook.worksheets;",
            "var activeWorksheet=worksheets.getActiveWorksheet();",
            "// >>>>>",
            "var copy=activeWorksheet.copy(...);",
            "// <<<<<"
        ],
        "fullStatements": [
            "Please enable config.extendedErrorLogging to see full statements."
        ]
    }
}

**Comment by J-January** [comment]
Thanks for reporting this, our team has started investigate for the issue.

**Comment by J-January** [comment]
Update:

This behavior is by-design, “Before” or “After” must come with the second parameter relativeTo, so the API know before or after which sheet. If the user wants the sheet to be copied before or after itself, he need call the API like _sheet.copy("Before", sheet);_    rather than  _sheet.copy("Before");_.

The document may have some ambiguity, we will update that.

**Comment by kbrandl** [comment]
@AlexJerabek I've assigned this one back to you, so that you can transfer it to **office-js-docs-pr**, if you think the docs need to be updated per the info above.
